### ISSUE TITLE
Menu items with routerLinks do not work/are not visible in pTable's context menu in latest PrimeNG LTS v9.2.7

### ISSUE THREAD

**Issue by gschafra** [primefaces/primeng#10213]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Sorry, after spending hours to get PrimeNG managed to run unsuccessfully on either stackblitz as well as codesandbox (very annoying), I only can provide an example project: 

https://github.com/gschafra/primeng-table-contextmenu-with-routelink-bug

**Current behavior**
When providing a context menu with menu items containing a routerLink (array value)...
```
[
      {
        label: 'View',
        icon: 'pi pi-fw pi-search',
        routerLink: ['1']
      },
      {
        label: 'Delete',
        icon: 'pi pi-fw pi-times',
        command: () => this.deleteProduct(this.selectedProduct)
      }
    ];
```
...the entry is not shown and causing the browser throwing 
```
ERROR DOMException: Failed to execute 'setAttribute' on 'Element': 'fragment]' is not a valid attribute name.
    at DefaultDomRenderer2.setAttribute (http://localhost:4200/vendor.js:68153:16)
    at setUpAttributes (http://localhost:4200/vendor.js:19107:53)
    at Module.ɵɵelementStart (http://localhost:4200/vendor.js:34070:9)
    at ContextMenuSub_ng_template_2_li_1_a_3_Template (http://localhost:4200/vendor.js:113085:65)
    at executeTemplate (http://localhost:4200/vendor.js:25402:9)
    at renderView (http://localhost:4200/vendor.js:25172:13)
    at TemplateRef.createEmbeddedView (http://localhost:4200/vendor.js:28773:17)
```

**Expected behavior**
Menu item with an valid routerLink is shown, which is the case in PrimeNG v7 LTS as well as v11!

**Minimal reproduction of the problem with instructions**
Try right click on a table row to open the context menu, which shows just one instead of the expected context menu entries.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, Yarn v1.22.5

* **Angular version:** 9.1

* **PrimeNG version:** 9.2.7 LTS

* **Browser:** Chrome 90, Firefox 88
 
* **Language:** TypesScript 3.8

* **Node (for AoT issues):** `node --version` =  v12.22.1

**Comment by yigitfindikli** [comment]
Fixed for v9.2.8.

**Comment by gschafra** [comment]
Wow, that's REALLY fast. Thanks a lot!

**Comment by yigitfindikli** [comment]
You're welcome! V9.2.8 released https://www.npmjs.com/package/primeng-lts/v/9.2.8
