### ISSUE TITLE
NPM install error on a fresh git clone - Incorrect dependencies for jspdf and jasmine-core

### ISSUE THREAD

**Issue by vivek201** [primefaces/primeng#10440]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
No plunkr repro because the error occurs during `npm install`

**Current behavior**

During NPM install, there are missing dependencies for the packages `jspdf` and `jasmine-core`

**Expected behavior**

NPM install would complete without having to make changes to `package.json`

**Minimal reproduction of the problem with instructions**

- Clone the repo in a new folder
- Run `npm install`

**What is the motivation / use case for changing the behavior?**

A fresh clone should be able to run `npm install` without any issues or changes to `package.json`

**Please tell us about your environment:**

Windows 10

* **Angular version:** 12.X

* **PrimeNG version:** 12.0.2 (master branch)

* **Browser:** [all]

 
* **Language:** [all]

* **Node (for AoT issues):** `node --version` = 14.17.3
* **NPM:** 7.14.0

**Comment by waratah** [comment]
In order to build I have to update the following:

"gulp": "^4.0.2",
"jasmine-core": "~3.8.0",
"jspdf": "^2.3.1",
"rxjs": "^6.5.3",

I also had to replace the gulp.js (note not a gulp expert but it worked)

```
'use strict';

var gulp = require('gulp'),
    concat = require('gulp-concat'),
    uglifycss = require('gulp-uglifycss'),
    rename = require('gulp-rename'),
    del = require('del'),
    flatten = require('gulp-flatten');

gulp.task('build-css', function() {
	return gulp.src([
        'src/app/components/common/common.css',
		    'src/app/components/**/*.css'
    ])
        .pipe(concat('primeng.css'))
        .pipe(gulp.dest('dist/resources'));
});

gulp.task('build-css-prod', function() {
    return gulp.src([
        'src/app/components/common/common.css',
        'src/app/components/badge/badge.css',
        'src/app/components/button/button.css',
        'src/app/components/checkbox/checkbox.css',
        'src/app/components/colorpicker/colorpicker-images.css',
        'src/app/components/inputtext/inputtext.css',
        'src/app/components/inputtextarea/inputtextarea.css',
        'src/app/components/password/password.css',
        'src/app/components/radiobutton/radiobutton.css',
        'src/app/components/ripple/ripple.css',
        'src/app/components/tooltip/tooltip.css'
    ])
    .pipe(concat('primeng.css'))
    .pipe(gulp.dest('dist/resources'))
    .pipe(uglifycss({"uglyComments": true}))
    .pipe(rename('primeng.min.css'))
    .pipe(gulp.dest('dist/resources'));
});

gulp.task('copy-component-css', function () {
    return gulp.src([
        'src/app/components/**/*.css',
        'src/app/components/**/images/*.png',
        'src/app/components/**/images/*.gif'
    ])
    .pipe(gulp.dest('dist/resources/components'));
});

gulp.task('images', function() {
    return gulp.src(['src/app/components/**/images/*.png', 'src/app/components/**/images/*.gif'])
        .pipe(flatten())
        .pipe(gulp.dest('dist/resources/images'));
});

gulp.task('themes', function() {
    return gulp.src(['src/assets/components/themes/**/*',
        '!src/assets/components/themes/soho-*/**/*',
        '!src/assets/components/themes/viva-*/**/*',
        '!src/assets/components/themes/mira/**/*',
        '!src/assets/components/themes/nano/**/*'])
        .pipe(gulp.dest('dist/resources/themes'));
});

//Cleaning previous gulp tasks from project
gulp.task('clean', function() {
	return del(['dist/resources']);
});

//Copy readme
gulp.task('readme', function() {
    return gulp.src(['README.md'])
    .pipe(gulp.dest('dist'));
});

//Building project with run sequence
gulp.task('build-assets', gulp.series('clean','copy-component-css', 'build-css-prod', 'images', 'themes', 'readme'));

```

**Comment by waratah** [comment]
reason for the gulp update was the following error:

```
Build at: 2021-12-07T01:50:42.859Z - Time: 121502ms

fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/ken/source/GitHub/primengMenu/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/ken/source/GitHub/primengMenu/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/ken/source/GitHub/primengMenu/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)

```

**Comment by waratah** [comment]
Pull request:  https://github.com/primefaces/primeng/pull/10930
