### ISSUE TITLE
p-dropdown throws an error when running tests: "TypeError: Cannot set property scrollHeight of [object Element] which has only a getter"

### ISSUE THREAD

**Issue by aironhight** [primefaces/primeng#10750]
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
<!-- Describe how the bug manifests. -->
I get an error when running 'ng test' with Karma. The component that contains p-dropdown throws the following error:
`Chrome 94.0.4606.81 (Windows 10) *componentName* should create FAILED
        TypeError: Cannot set property scrollHeight of [object Element] which has only a getter
            at EmulatedEncapsulationDomRenderer2.setProperty (node_modules/@angular/platform-browser/__ivy_ngcc__/fesm2015/platform-browser.js:745:1)
            at elementPropertyInternal (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10033:1)
            at ɵɵproperty (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14794:1)
            at PeriodManagerComponent_div_10_div_2_Template (ng:///PeriodManagerComponent.js:136:105)
            at executeTemplate (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9606:1)
            at refreshView (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9472:1)
            at refreshEmbeddedViews (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10597:1)
            at refreshView (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9496:1)
            at refreshEmbeddedViews (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10597:1)`

**Expected behavior**
Should not throw an error

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/github-4tisbc?file=src/app/app.component.html
Run 'ng test' with Jasmine/Karma.

**What is the motivation / use case for changing the behavior?**
To not throw errors.

**Please tell us about your environment:**
"primeng": "^11.4.0"
"jasmine-core": "~3.9.0",
"jasmine-spec-reporter": "~7.0.0",
"karma": "~6.3.4",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage-istanbul-reporter": "~3.0.3",
"karma-jasmine": "~4.0.1",
"karma-jasmine-html-reporter": "^1.7.0",

* **Angular version:** 5.X
<!-- Check whether this is still an issue in the most recent Angular version -->

* **PrimeNG version:** 5.X
"@angular/cdk": "^12.2.10"	

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 94.0.4606.81

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^4.3.5"


* **Node (for AoT issues):** `node --version` = v14.16.1

**Comment by yigitfindikli** [comment]
You need to import DropdownModule in your spec.ts as well.
