### ISSUE TITLE
PrimeNG - Tree Max Call Size.

### ISSUE THREAD

**Issue by DazedDragon** [primefaces/primeng#11307]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
``
**Current behavior**
When building the model that is to be used for the tree, i make sure that each entry has a unique key assigned and have double checked this with the console output. I have discovered there seems to be some max call size only when filtering data as this doesn't fully initialize the click event. When the list is unfiltered i am able to click the node that i want and carry on with the process.

**Expected behavior**
I should be able to click the node and add it to my model.

**Minimal reproduction of the problem with instructions**
Once the tree is built i filter based on the project. I select the node but get a console output saying:
core.js:6210 ERROR RangeError: Maximum call stack size exceeded
    at Tree.syncNodeOption (primeng-tree.js:1186:1)
    at Tree.propagateUp (primeng-tree.js:1237:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)
    at Tree.propagateUp (primeng-tree.js:1241:1)

This doesnt happen when the tree has no filter.


* **Angular version:** 5.X
v11.2.3

* **PrimeNG version:** 5.X
11.4.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->
 
TS 4.0.7

* **Node (for AoT issues):** `node --version` =   v12

**Comment by cetincakiroglu** [comment]
Hi, 

The issue is not clear, please provide a StackBlitz example by using https://stackblitz.com/github/primefaces/primeng-issue-template and re-open the issue.

Regards
