### ISSUE TITLE
Overlay with hideTransitionOptions leads to TypeError: Cannot read properties of null (reading 'offsetHeight')

### ISSUE THREAD

**Issue by HaraldStiwa** [primefaces/primeng#11405]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
Please demonstrate your case at stackblitz by using the issue template below. Issues without a test case have much less possibility to be reviewd in detail and assisted.

[https://stackblitz.com/edit/primeng-overlaypanel-demo-28reg8?file=src%2Fapp%2Fapp.component.html
](https://stackblitz.com/edit/primeng-overlaypanel-demo-28reg8?file=src%2Fapp%2Fapp.component.html)

**Current behavior**

Multiple fast clicks on the button lead to errors in console/website:
```
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.. Find more at https://angular.io/errors/NG0100
    at new RuntimeError (stringify_utils.ts:15:33)
    at throwErrorIfNoChangesMode (view_traversal_utils.ts:78:1)
    at bindingUpdated (attribute_interpolation.ts:293:1)
    at ɵɵproperty (listener.ts:169:38)
    at OverlayPanel_Template (ɵcmp.js? [sm]:2:15)
    at executeTemplate (shared.ts:980:7)
    at refreshView (shared.ts:836:13)
    at refreshComponent (change_detection.ts:15:1)
    at refreshChildComponents (shared.ts:573:4)
    at refreshView (shared.ts:887:9)

ERROR TypeError: Cannot read properties of null (reading 'offsetHeight')
    at Function.DomHandler.absolutePosition (domhandler.ts:152:27)
    at OverlayPanel.align (overlaypanel.ts:241:18)
    at OverlayPanel.onAnimationStart (overlaypanel.ts:262:13)
    at OverlayPanel_div_0_Template_div_animation_animation_start_0_listener (ɵcmp.js? [sm]:2:109)
    at executeListenerWithErrorHandling (property_interpolation.ts:303:1)
    at wrapListenerIn_markDirtyAndPreventDefault (property_interpolation.ts:361:1)
    at eval (animation_renderer.ts:182:4)
    at Array.forEach (<anonymous>)
    at eval (animation_renderer.ts:180:42)
    at ZoneDelegate.invoke (zone.js:400:30)
```

**Expected behavior**

No errors.

**Minimal reproduction of the problem with instructions**

1. Open StackBlitz URL from above
2. Click button multiple times
3. Open DevTools console

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 13.2.4

* **PrimeNG version:** 13.2.0

* **Browser:** Google Chrome 100.0.4896.75 / MS Edge 100.0.1185.36 / Firefox 99.0 / etc.
 
* **Language:** Typescript 4.5.5

* **Node (for AoT issues):** `node --version` =  v16.14.0

**Comment by HaraldStiwa** [comment]
Please note the `[hideTransitionOptions]="'1s linear'"` option.
