### ISSUE TITLE
p-orderList doesn't work

### ISSUE THREAD

**Issue by paris0120** [primefaces/primeng#11537]
I'm submitting a ...**  (check one with "x")
```
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
I'm trying to use p-orderList, but got errors like the following (Even the simpliest demo from https://www.primefaces.org/primeng/orderlist) 

core.mjs:6494 ERROR TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:20639:1)
    at Object.definition.providersResolver (core.mjs:20894:1)
    at resolveDirectives (core.mjs:10224:1)
    at elementStartFirstCreatePass (core.mjs:14512:1)
    at Module.ɵɵelementStart (core.mjs:14550:1)
    at OrderList_Template (primeng-orderlist.mjs:355:17)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
defaultErrorLogger @ core.mjs:6494
handleError @ core.mjs:6541
(anonymous) @ core.mjs:26295
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25507
(anonymous) @ core.mjs:26295
invoke @ zone.js:372
onInvoke @ core.mjs:25608
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:25595
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1450
bootstrapModule @ core.mjs:26214
14431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:71
(anonymous) @ main.js:2
main.ts:12 TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:20639:1)
    at Object.definition.providersResolver (core.mjs:20894:1)
    at resolveDirectives (core.mjs:10224:1)
    at elementStartFirstCreatePass (core.mjs:14512:1)
    at Module.ɵɵelementStart (core.mjs:14550:1)
    at OrderList_Template (primeng-orderlist.mjs:355:17)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)

and if I add dragdrop="true", I got 

TS2322: Type 'string' is not assignable to type 'boolean'.

9   dragdrop="true"

**Current behavior**

core.mjs:6494 ERROR TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:20639:1)
    at Object.definition.providersResolver (core.mjs:20894:1)
    at resolveDirectives (core.mjs:10224:1)
    at elementStartFirstCreatePass (core.mjs:14512:1)
    at Module.ɵɵelementStart (core.mjs:14550:1)
    at OrderList_Template (primeng-orderlist.mjs:355:17)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)
defaultErrorLogger @ core.mjs:6494
handleError @ core.mjs:6541
(anonymous) @ core.mjs:26295
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25507
(anonymous) @ core.mjs:26295
invoke @ zone.js:372
onInvoke @ core.mjs:25608
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:25595
invokeTask @ zone.js:405
runTask @ zone.js:178
drainMicroTaskQueue @ zone.js:585
Promise.then (async)
nativeScheduleMicroTask @ zone.js:561
scheduleMicroTask @ zone.js:572
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1265
then @ zone.js:1450
bootstrapModule @ core.mjs:26214
14431 @ main.ts:11
__webpack_require__ @ bootstrap:19
__webpack_exec__ @ main.ts:12
(anonymous) @ main.ts:12
__webpack_require__.O @ chunk loaded:23
(anonymous) @ main.ts:12
webpackJsonpCallback @ jsonp chunk loading:71
(anonymous) @ main.js:2
main.ts:12 TypeError: Cannot read properties of null (reading 'firstCreatePass')
    at providersResolver (core.mjs:20639:1)
    at Object.definition.providersResolver (core.mjs:20894:1)
    at resolveDirectives (core.mjs:10224:1)
    at elementStartFirstCreatePass (core.mjs:14512:1)
    at Module.ɵɵelementStart (core.mjs:14550:1)
    at OrderList_Template (primeng-orderlist.mjs:355:17)
    at executeTemplate (core.mjs:9632:1)
    at renderView (core.mjs:9432:1)
    at renderComponent$1 (core.mjs:10739:1)
    at renderChildComponents (core.mjs:9297:1)

and 

TS2322: Type 'string' is not assignable to type 'boolean'.

9   dragdrop="true"

 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 11, IJ, npm

* **Angular version:** 5.X
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
rxjs                            7.5.5
typescript                      4.6.4

* **PrimeNG version:** 5.X
primeng@13.4.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =   
v16.14.2

**Comment by paris0120** [comment]
PickList has the same problem.

**Comment by cetincakiroglu** [comment]
Hi,

Cannot replicate the issue with the versions from 7 to 13.4.0, as you see it works on StackBlitz demo. https://stackblitz.com/edit/primeng-orderlist-demo?file=src%2Fapp%2Fapp.component.ts

Please provide a StackBlitz example and re-open the issue.

Regards
