### ISSUE TITLE
Getting 'PrimeTemplate' is neither 'ComponentType' or 'DirectiveType'. error with Fileupload option

### ISSUE THREAD

**Issue by yobindra** [primefaces/primeng#11691]
ERROR Error: 'PrimeTemplate' is neither 'ComponentType' or 'DirectiveType'.
    at extractDirectiveDef (core.js:956:1)
    at Array.map (<anonymous>)
    at def.directiveDefs (core.js:931:1)
    at createTView (core.js:9732:1)
    at getOrCreateTComponentView (core.js:9680:1)
    at createRootComponentView (core.js:12451:1)
    at ComponentFactory$1.create (core.js:25106:1)
    at ViewContainerRef.createComponent (core.js:23180:1)
    at DynamicFieldDirective.ngOnInit (dynamic-form.js:4235:1)
    at callHook (core.js:2573:1)

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
