### ISSUE TITLE
[p-dialog]: Doesn't work with Angular Universal

### ISSUE THREAD

**Issue by btd1337** [primefaces/primeng#11726]
### Describe the bug

The dialog component is not working with Angular Universal.

```
ReferenceError: window is not defined
    at Dialog.unbindDocumentDragListener (/dist/project/server/main.js:186376:7)
    at Dialog.unbindGlobalListeners (/dist/project/server/main.js:186361:10)
    at Dialog.onContainerDestroy (/dist/project/server/main.js:186488:10)
    at Dialog.ngOnDestroy (/dist/project/server/main.js:186524:12)
    at executeOnDestroys (/dist/project/server/main.js:144691:32)
    at cleanUpView (/dist/project/server/main.js:144594:9)
    at destroyViewTree (/dist/project/server/main.js:144420:21)
    at destroyLView (/dist/project/server/main.js:144572:9)
    at RootViewRef.destroy (/dist/project/server/main.js:158610:9)
    at /dist/project/server/main.js:163939:52
```

### Environment

macOS Monterey: 12.4

### Angular version

13.3.4

### PrimeNG version

13.4.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.2

### Steps to reproduce the behavior

Try to use `p-dialog` in Angular Universal

### Expected behavior

Correctly use dialog component in Angular Universal

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
