### ISSUE TITLE
Tabmenu: Error on SSR

### ISSUE THREAD

**Issue by Jonnyprof** [primefaces/primeng#11871]
### Describe the bug

Tabmenu throws an error in Server Side Rendering, when calling `updateInkBar` method in `ngAfterViewInit` hook.
https://github.com/primefaces/primeng/blob/085a6040181e6a2c4091c56ff7b9be79111dbb71/src/app/components/tabmenu/tabmenu.ts#L110-L114

The error is `ReferenceError: getComputedStyle is not defined`.
IMHO `ngAfterViewInit` methods (updateInkBar, initAutoScrollForActiveItem, initButtonState) should be executed only in browser side.

### Environment

Any environment

### Angular version

14.1.3

### PrimeNG version

14.0.2

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.17.0

### Steps to reproduce the behavior

In a project with SSR, place an tabmenu component and visit the page.

### Expected behavior

Tabmenu component should work properly on SSR.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap? 
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,

**Comment by Jonnyprof** [comment]
This is still happening in v14.2.1, so `updateInkBar` method still has manipulating DOM and this method is still being called from `ngAfterViewInit` hook.

@mertsincan please, reopen it.

**Comment by MaksymShchukin** [comment]
same method `updateInkBar` also fails in TabView on SSR with the same error

**Comment by D-Biela** [comment]
Yep many components throw errors when using Angular Universal. I guess my company has to switch to another Framework:

ERROR ReferenceError: getComputedStyle is not defined
    at getWidth (./node_modules/primeng/fesm2020/primeng-dom.mjs:342:21)
    at updateInkBar (./node_modules/primeng/fesm2020/primeng-tabview.mjs:287:53)
    at ngAfterViewChecked (./node_modules/primeng/fesm2020/primeng-tabview.mjs:163:18)

**Comment by SOG-web** [comment]
still getting this error in v16.0.0-rc.2
Angular v16

**Comment by alvarocastillop** [comment]
this errors still happend in angular 16.2.10 and Primeng 16.5.1
