### ISSUE TITLE
Tooltip problems.

### ISSUE THREAD

**Issue by Xamlware** [primefaces/primeng#1199]
I'm using beta.17 because of the problem with calendar displaying initial date.  I added tooltips to a couple of buttons today ( haven't used them before):
```
<p-column>
   <template let-col let-row="rowData" pTemplate type="body">
      <div>
	<button pButton type="button" (click)="deleteRow(row['index'])" icon="fa fa-trash-o" pTooltip="Delete this item" tooltipPosition="bottom"></button>
	<button pButton class="homeButton" (click)="showDialog()" icon="fa fa-list-alt" pTooltip="Display extended list" tooltipPosition="bottom"></button>
      </div>
   </template>
</p-column>

```
If you hover over one of the tooltips, it display correctly however this error occurs when you move the mouse to another control.

```
TypeError: Unable to get property 'style' of undefined or null reference
   at Tooltip.prototype.hide (http://localhost:4200/main.bundle.js:89411:9)
   at Tooltip.prototype.onMouseLeave (http://localhost:4200/main.bundle.js:89366:13)
   at _View_FoodDiaryComponent1.prototype._handle_mouseleave_3_2 (Function code:3198:3)
   at Anonymous function (http://localhost:4200/main.bundle.js:68822:17)
   at Anonymous function (http://localhost:4200/main.bundle.js:38424:9)
   at Anonymous function (http://localhost:4200/main.bundle.js:52866:104)
   at ZoneDelegate.prototype.invoke (http://localhost:4200/main.bundle.js:97371:13)
   at onInvoke (http://localhost:4200/main.bundle.js:36514:21)
   at ZoneDelegate.prototype.invoke (http://localhost:4200/main.bundle.js:97371:13)
   at Zone.prototype.runGuarded (http://localhost:4200/main.bundle.js:97269:21)
```

Problem 2:
If you scroll the screen, the tooltip displays at the location where the control was, not where it is now.  This also happens on your demo site at primfaces.org/priming.

**Comment by akuzkou** [comment]
Issue is actual in 1.1.1

This issue has been reproduced with IE11 (11.0.9600.17420) in VirtualBox:
IE11 on Win7 (VirtualBox) downloaded from Microsoft official site:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
