### ISSUE TITLE
Live Examples not working for DataTable

### ISSUE THREAD

**Issue by derchirurg** [primefaces/primeng#1203]
On the demo site http://www.primefaces.org/primeng/#/ the links of "live expample" does not work.
(Example: http://www.primefaces.org/primeng/#/datatabletemplating)

Stacktrace of console:

vendor.js:2 EXCEPTION: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'datatabletemplating'
Error: Cannot match any routes. URL Segment: 'datatabletemplating'
    at ApplyRedirects.noMatchError (http://www.primefaces.org/primeng/prod/vendor.js:12:12347)
    at CatchSubscriber.selector (http://www.primefaces.org/primeng/prod/vendor.js:12:12018)
    at CatchSubscriber.error (http://www.primefaces.org/primeng/prod/vendor.js:14:1762)
    at MapSubscriber.Subscriber._error (http://www.primefaces.org/primeng/prod/vendor.js:5:11509)
    at MapSubscriber.Subscriber.error (http://www.primefaces.org/primeng/prod/vendor.js:5:11167)
    at MapSubscriber.Subscriber._error (http://www.primefaces.org/primeng/prod/vendor.js:5:11509)
    at MapSubscriber.Subscriber.error (http://www.primefaces.org/primeng/prod/vendor.js:5:11167)
    at MapSubscriber.Subscriber._error (http://www.primefaces.org/primeng/prod/vendor.js:5:11509)
    at MapSubscriber.Subscriber.error (http://www.primefaces.org/primeng/prod/vendor.js:5:11167)
    at LastSubscriber.Subscriber._error (http://www.primefaces.org/primeng/prod/vendor.js:5:11509)

**Comment by garethlewis** [comment]
That's because there isn't a route called datatabletemplating,

The url is http://www.primefaces.org/primeng/#/datatable/templating

**Comment by cagataycivici** [comment]
Works as expected.

**Comment by derchirurg** [comment]
Sorry, but it does not work as expected.
If I hit the link of "live expample", there is the wrong link in there (http://www.primefaces.org/primeng/#/datatabletemplating)

Please see my picture.
![wrong link](https://cloud.githubusercontent.com/assets/22213966/20054219/3b651996-a4dc-11e6-91a3-fc6023813316.PNG)

I think the route is build wrong. A slash is missing.

**Comment by cagataycivici** [comment]
I see what you are referring to, commited a fix, thank you.
