### ISSUE TITLE
Component: p-calendar type error when [showTime]="true" and [keepInvalid]="true"

### ISSUE THREAD

**Issue by matusko89** [primefaces/primeng#12329]
### Describe the bug

When using calendar with showtime and keepInvalid set to true, if you manualy enter a wrong date formate to the input and the open the calendar and try to change time you get type error:
TypeError: value.toDateString is not a function
at Calendar.validateTime (primeng-calendar.mjs:1380:47)
at Calendar.incrementMinute (primeng-calendar.mjs:1506:18)
at Calendar.repeat (primeng-calendar.mjs:1466:26)
at Calendar.onTimePickerElementMouseDown (primeng-calendar.mjs:1434:18)
at Calendar_div_3_div_5_Template_button_mousedown_13_listener (primeng-calendar.mjs:2398:204)

I am once again submitting the bug report as from the first  issue that I created a added a wrong stackbliz link and it was closed

### Environment

not related to enviroment

### Reproducer

https://stackblitz.com/edit/github-5nuyt1?file=src/app/app.component.html

### Angular version

14.1.0

### PrimeNG version

14.0.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.13.2

### Steps to reproduce the behavior

1. enter some string that is not valid date to calendar input
2. open calendar selector
3. change the time

### Expected behavior

should set current date and adjust time

**Comment by matusko89** [comment]
Any update on this issue?

**Comment by fast-typing** [comment]
i have the same issue but i didnt use [keepInvalid]="true" just [showTime]="true". This happened cause the wrong date format, i think primeng trying to change time, but you give the invalid date and it cause error. sry for my english

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you reopen the issue so we can include it in our roadmap?
Please don't forget to add your feedback as a comment after reopening the issue. These will be taken into account by us and will contribute to the development of this feature. Thanks a lot for your understanding!

Best Regards,
