### ISSUE TITLE
TreeTable: p-treetable tab navigation not working properly

### ISSUE THREAD

**Issue by RafalKowalik** [primefaces/primeng#12513]
### Describe the bug

I'm having an issue when tab key is used on editable tree table component. 
Problem appears when you have at least one non-editable column (no matter if its the value-like column or action buttons column)
It can be reproduced on 
v13 [https://stackblitz.com/edit/primeng-tableedit-demo-1vgsaa](url)
v14 [https://stackblitz.com/edit/primeng-treetableedit-demo-mmaoah](url)

### Environment

Windows 10

### Reproducer

https://stackblitz.com/edit/primeng-tableedit-demo-1vgsaa

### Angular version

13

### PrimeNG version

13

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

### Browser(s)

Chrome

### Steps to reproduce the behavior

- click on non-editable column in aforementioned example (i.e 75kb)
- press tab key for the first time (focus should be set on the first input field)
- press tab key for the second time - error is thrown in the console

`ERROR TypeError: Cannot read properties of null (reading 'parentElement')
    at TTEditableColumn.moveToNextCell (treetable.ts:2756:44)
    at TTEditableColumn.onKeyDown (treetable.ts:2723:26)
    at TTEditableColumn_keydown_HostBindingHandler (ɵfac.js:0:0)
    at executeListenerWithErrorHandling (style_binding_list.ts:1:1)
    at wrapListenerIn_markDirtyAndPreventDefault (style_binding_list.ts:18:1)
    at HTMLTableCellElement.eval (dom_renderer.ts:167:27)
    at _ZoneDelegate.invokeTask (zone.js:443:35)
    at Object.onInvokeTask (application_ref.ts:615:1)
    at _ZoneDelegate.invokeTask (zone.js:442:64)
    at Zone.runTask (zone.js:214:51)`

### Expected behavior

tab navigation should work properly for tree-table component, no error in console

**Comment by mehmetcetin01140** [comment]
Hi,

The issue you mentioned seems to appear in an outdated version of ours. Between the version you referred to and our current version (v17x), we've made numerous improvements, bug fixes, and enhancements, so the issue might have been addressed. If you encounter it in the current version as well, please open an issue with a Stackblitz example.
