### ISSUE TITLE
Dropdown and Multiselect Problem after upgrade to Angular 15 and Primeng 15

### ISSUE THREAD

**Issue by ajobra76** [primefaces/primeng#12524]
### Describe the bug

After Click on all Multiselects or all Dropdowns following Error Occurs
core.mjs:8506 ERROR TypeError: value.trim is not a function
    at set klass [as klass] (common.mjs:2641:53)
    at setInputsForProperty (core.mjs:11741:34)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:13650:5)
    at checkStylingMap (core.mjs:15612:13)
    at Module.ɵɵclassMap (core.mjs:15529:5)
    at Overlay_div_0_Template (primeng-overlay.mjs:358:93)
    at executeTemplate (core.mjs:10534:9)
    at refreshView (core.mjs:10419:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
    at refreshView (core.mjs:10443:9)

### Environment

Windows
Main Project and Minimal Project

### Angular version

15

### PrimeNG version

15.0.1 and 15.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.3.0

### Browser(s)

chrome,firefox

**Comment by NahiaLC** [comment]
Same problem here!

Angular v15.1.1
PrimeNG v15.1.0
Node v16.15.1

**Comment by jimguistwite** [comment]
I've downgraded to Angular v15.1.0 to work around the issue.

**Comment by magicdict** [comment]
I've downgraded to Angular v15.1.0 to work around the issue. +1

**Comment by NahiaLC** [comment]
Same issue in Angular v15.1.0

**Comment by sathyesh** [comment]
Same issue

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/12525#issuecomment-1398509094

**Comment by coridrew** [comment]
same issue

**Comment by mertsincan** [comment]
Please try the latest version.

**Comment by coridrew** [comment]
That fixed it thank you
