### ISSUE TITLE
Table: Filter-Menue raises errors

### ISSUE THREAD

**Issue by wiedehoeft** [primefaces/primeng#12538]
### Describe the bug

When applying the `display="menu"` on any column of p-table i get following error, when using menues for "Match All" and "Starts With":
```
core.mjs:8506 ERROR TypeError: value.trim is not a function
    at set klass [as klass] (common.mjs:2641:53)
    at setInputsForProperty (core.mjs:11741:34)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:13650:5)
    at checkStylingMap (core.mjs:15612:13)
    at Module.ɵɵclassMap (core.mjs:15529:5)
    at Overlay_div_0_Template (primeng-overlay.mjs:358:93)
    at executeTemplate (core.mjs:10534:9)
    at refreshView (core.mjs:10419:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
    at refreshView (core.mjs:10443:9)core.mjs:8506 ERROR TypeError: value.trim is not a function
    at set klass [as klass] (common.mjs:2641:53)
    at setInputsForProperty (core.mjs:11741:34)
    at setDirectiveInputsWhichShadowsStyling (core.mjs:13650:5)
    at checkStylingMap (core.mjs:15612:13)
    at Module.ɵɵclassMap (core.mjs:15529:5)
    at Overlay_div_0_Template (primeng-overlay.mjs:358:93)
    at executeTemplate (core.mjs:10534:9)
    at refreshView (core.mjs:10419:13)
    at refreshEmbeddedViews (core.mjs:11434:17)
    at refreshView (core.mjs:10443:9)
```

I could reproduce it with example from here:
https://primefaces.org/primeng/table

The filter can still be used and applied, but changing the values from the first two menu entries is not possible.
At this moment I think of incompatibility of Angular/Primeng/Typescript => Just downgraded my application to Angular 14.2.12 and primeng 14.2.2 and the error disappears.

### Environment

Angular application with following dependencies:
```
    "@angular/animations": "^15.1.1",
    "@angular/common": "^15.1.1",
    "@angular/compiler": "^15.1.1",
    "@angular/core": "^15.1.1",
    "@angular/forms": "^15.1.1",
    "@angular/platform-browser": "^15.1.1",
    "@angular/platform-browser-dynamic": "^15.1.1",
    "@angular/router": "^15.1.1",
    "primeflex": "~3.3.0",
    "primeicons": "^6.0.1",
    "primeng": "^15.1.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.12.0"
```

### Angular version

15.1.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.12.1

### Expected behavior

The filter menu should work and throw no errors.

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primeng/issues/12525
