### ISSUE TITLE
p-checkbox - throws an error within reactive forms

### ISSUE THREAD

**Issue by EnricoVogt** [primefaces/primeng#12666]
I have a FormModel like this:
```
    protected configForm = this.formBuilder.group({
        active: [true, [],
    });
```
As mentioned in the docs im using:
```
<!-- Correct -->
<p-checkbox [formControl]="configForm.controls['active']"></p-checkbox>
```

Problems i encounter:
- the state of the checkbox is not reflected initially
- if the checkbox is clicked the following error appears:
```
core.mjs:8506 ERROR TypeError: this.model is not iterable
    at Checkbox.updateModel (primeng-checkbox.mjs:40:55)
    at Checkbox.onClick (primeng-checkbox.mjs:29:14)
    at Checkbox_Template_div_click_4_listener (primeng-checkbox.mjs:110:50)
    at executeListenerWithErrorHandling (core.mjs:14090:16)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:14123:22)
    at HTMLDivElement.<anonymous> (platform-browser.mjs:402:38)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
```

### Environment

Angular: 15.1.1
PrimeNG: 15.1.0

### Reproducer

https://stackblitz.com/edit/github-dgf3op?file=src/app/app.component.html

### Angular version

15.1.1

### PrimeNG version

15.1.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

16.14.0

**Comment by volvachev** [comment]
Hi, you need to add this attribute to your example

```html
binary="true"
```

```html
<div [formGroup]="jobConfigForm">
  <div class="field col">
    <label for="active" style="width:150px">
      <span>active</span>
    </label>
    <div>
      <p-checkbox
        id="active"
        binary="true"
        [formControl]="jobConfigForm.controls['active']"
      ></p-checkbox>
    </div>
  </div>
</div>

```
