### ISSUE TITLE
ConfirmPopup: TypeError: Cannot read properties of null (reading 'target')

### ISSUE THREAD

**Issue by oidacra** [primefaces/primeng#13125]
### Describe the bug

When you try to test a component using ConfirmPopup with Jest shows the following error:

`TypeError: Cannot read properties of null (reading 'target')`

After multiple debug the problem comes from
 
```
this.confirmationService.confirm({
            target: $event.target,   <--- here  
            message: 'Message',
            icon: 'pi pi-exclamation-triangle',
            acceptLabel: 'stop label',
            rejectLabel: 'reject label',
            accept: () => {
                this.acceptMethodToCall()
            }
        });
```

Stack Trace
```
 at ConfirmPopup.bindScrollListener (../../../../node_modules/primeng/fesm2015/primeng-confirmpopup.mjs:170:86)
      at ../../../../node_modules/primeng/fesm2015/primeng-confirmpopup.mjs:127:18
      at timer (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3090:47)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:441:35)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4696:33)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3793:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:440:64)
      at AsyncStackTaggingZoneSpec.onInvokeTask (../../../../node_modules/@angular/core/fesm2015/core.mjs:23996:28)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:440:64)
      at Object.onInvokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:319:104)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:440:64)
      at Object.onInvokeTask (../../../../node_modules/@angular/core/fesm2015/core.mjs:24294:33)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:440:64)
      at Zone.Object.<anonymous>.Zone.runTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:212:51)
      at Object.<anonymous>.ZoneTask.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:523:38)
      at ZoneTask.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:512:52)
      at data.args.<computed> (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3070:36)
      at Timeout.task [as _onTimeout] (../../../../node_modules/jsdom/lib/jsdom/browser/Window.js:514:19)
          at ____________________Elapsed_75_ms__At__Wed_May_31_2023_16_24_47_GMT_0400__Eastern_Daylight_Saving_Time_ (http://localhost)
      at Object.onScheduleTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3582:26)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.scheduleTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:421:55)
      at Object.onScheduleTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:318:84)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.scheduleTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:421:55)
      at Zone.Object.<anonymous>.Zone.scheduleTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:255:47)
      at Zone.Object.<anonymous>.Zone.scheduleMacroTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:278:29)
      at scheduleMacroTaskWithCurrentZone (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:723:29)
      at ../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3114:32
      at proto.<computed> (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1022:28)
      at ConfirmPopup.bindListeners (../../../../node_modules/primeng/fesm2015/primeng-confirmpopup.mjs:124:9)
      at ConfirmPopup.onAnimationStart (../../../../node_modules/primeng/fesm2015/primeng-confirmpopup.mjs:57:18)
      at ConfirmPopup_div_0_Template_div_animation_animation_start_0_listener (../../../../ng:/ConfirmPopup/ɵcmp.js:67:40)
      at executeListenerWithErrorHandling (../../../../node_modules/@angular/core/fesm2015/core.mjs:14085:16)
      at wrapListenerIn_markDirtyAndPreventDefault (../../../../node_modules/@angular/core/fesm2015/core.mjs:14118:22)
      at fn (../../../../node_modules/@angular/platform-browser/fesm2015/animations.mjs:195:25)
          at Array.forEach (<anonymous>)
      at ../../../../node_modules/@angular/platform-browser/fesm2015/animations.mjs:193:52
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Object.onInvoke (../../../../node_modules/@angular/core/fesm2015/core.mjs:24307:33)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at NgZone.run (../../../../node_modules/@angular/core/fesm2015/core.mjs:24161:28)
      at ../../../../node_modules/@angular/platform-browser/fesm2015/animations.mjs:192:28
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at ../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1325:38
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:441:35)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3796:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:440:64)
      at Zone.Object.<anonymous>.Zone.runTask (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:212:51)
      at drainMicroTaskQueue (../../../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:627:39)
```

### Environment

Angular: 15.1.2
Primeng: 15.4.3

### Angular version

15.1.2

### PrimeNG version

15.1.1

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

v16.14.2

**Comment by nairabh** [comment]
One work-around (that worked for me with ng v14) in case you're using htmlButtonElement.nativeElement.click() for your test-case, is changing it to trigger the click event instead like 'htmlButtonElement.triggerEventHandler('click', {})'.

**Comment by mehmetcetin01140** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
