### ISSUE TITLE
Component: ContextMenu

### ISSUE THREAD

**Issue by MarkBoote** [primefaces/primeng#13456]
### Describe the bug

when using appendTo 'body' (or any element for that matter) the menu throws errors (see chrome console) relating to animation.

### Environment

windows

### Angular version

16.1.8

### PrimeNG version

16.1.10

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.13.0

### Steps to reproduce the behavior

<div #jt>test</div>
<p-contextMenu [target]="jt" [appendTo]="'body'" [model]="test"></p-contextMenu>

...

  test: MenuItem[] = [
    {label: 'opt 1'},
    {label: 'opt 2'}
  ];

...
right click 'test', click an item, or anywhere outside of the context menu & error is thrown in the console:
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### Expected behavior

No error thrown

**Comment by MarkBoote** [comment]
> @MarkBoote can asked if you get solution for this isssue or still stuck in it

No solution yet (other than to not use appendTo)

**Comment by cetincakiroglu** [comment]
@oriebalzyuot96 could you please open an issue with the reproducer for that

**Comment by MarkBoote** [comment]
Also notice that this is causing problems with some of our unit tests (I suspect that the object under test has been destroyed before it gets chance to animate the contextmenu - happens regardless of what the contextmenu appendTo is):

ERROR: 'ERROR', TypeError: Cannot read properties of undefined (reading 'nativeElement')
TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at ContextMenu.position (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:957:45)     
    at ContextMenu.onOverlayAnimationStart (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:894:22)
    at listenerFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:1101:40)
    at executeListenerWithErrorHandling (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:15778:16)
    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:15811:22)
    at forEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2022/animations.mjs:190:25)
    at Array.forEach (<anonymous>)
    at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2022/animations.mjs:188:52)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:368:26)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:273:39)
ERROR: 'ERROR', TypeError: Cannot read properties of undefined (reading 'nativeElement')
TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at ContextMenu.position (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:957:45)     
    at ContextMenu.onOverlayAnimationStart (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:894:22)
    at listenerFn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/primeng/fesm2022/primeng-contextmenu.mjs:1101:40)
    at executeListenerWithErrorHandling (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:15778:16)    at fn (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:15811:22)
    at forEach (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2022/animations.mjs:190:25)
    at Array.forEach (<anonymous>)
    at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2022/animations.mjs:188:52)
    at _ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:368:26)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:273:39)

**Comment by MarkBoote** [comment]
looks like problem is in contextmenu.ts - position function:
        let width = this.containerViewChild.nativeElement.offsetParent ? this.containerViewChild.nativeElement.offsetWidth : DomHandler.getHiddenElementOuterWidth(this.containerViewChild.nativeElement);

containerViewChild has already been destroyed.

would be useful if exit animations could be disabled - they are of no use in the context of unit tests & most use cases in our scenario involve opening a modal dialogue which usually obscures the context menu, which means the animation will rarely, if ever, be seen by an end user.
