### ISSUE TITLE
16.7.0: Context Menu throws Type Error in a nested Table 

### ISSUE THREAD

**Issue by hugograf** [primefaces/primeng#14006]
### Describe the bug

Table has a nested table, this can be opened with an expanded row. A context menu is implemented on the outer and inner table. If the row is expanded and closed again, the following error message appears in the console:
```
vendor.js:75605 ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')
    at ContextMenu.removeAppendedElements (vendor.js:137562:107)
    at ContextMenu.ngOnDestroy (vendor.js:137568:10)
    at executeOnDestroys (vendor.js:72352:20)
    at cleanUpView (vendor.js:72264:5)
    at destroyViewTree (vendor.js:72096:11)
    at destroyLView (vendor.js:72242:5)
    at ViewContainerRef.remove (vendor.js:89132:7)
    at ViewContainerRef.clear (vendor.js:88981:12)
    at NgIf._updateView (vendor.js:58321:29)
    at set ngIf [as ngIf] (vendor.js:58290:10)
````
The context menu does not even have to be activated.

### Environment

Primeng 16.7.0
Angular 16.X

### Reproducer

https://stackblitz.com/edit/fpv3rx?file=package.json

### Angular version

16.X

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Steps to reproduce the behavior

See "Describe the bug" and use StackBlitz.

**Comment by jeremymlewis** [comment]
Looks like this bug was introduced in one trying to handle one of the following issues https://github.com/primefaces/primeng/issues/13948, https://github.com/primefaces/primeng/issues/13949, https://github.com/primefaces/primeng/issues/13936

**Comment by WienemannCC** [comment]
We are experiencing this without nested tables just on route changes. Completely breaks the application.

**Comment by derdrennan** [comment]
I just want to recap what I've seen from tracking this issue. Starting in 16.1.0 the context menu would not close if you routed to another page. If you had a context menu open, then routed to a different page, it would be stuck on the screen until you refreshed the browser. There was a discussion about this starting on Oct 2 (https://github.com/orgs/primefaces/discussions/161). A bug case was created for it and the 3 issues Jeremy linked were all related. 

There was a fix rolled out #13960 but after we pulled those changes, the issue mentioned in this case started happening. And just to echo what @WienemannCC is saying, it breaks the application on route changes for us now as well.

**Comment by cetincakiroglu** [comment]
Thanks a lot for reporting the issue!

**Comment by dnordahl1** [comment]
I was hoping this would also end up fixing https://github.com/primefaces/primeng/issues/13934  but it doesn't appear to have done so. When I was trying to find a work around I was able to get the menu to stop requiring two clicks by putting something in the appendTo which is invalid and throws an error (which of course does make the menu render strangely).  So I was thinking it might be related to the appendTo parameter more than menu being within a table.  Leaving off appendTo results in the menu not being anywhere I can click it so I can't tell for certain if this is the primary factor.
