### ISSUE TITLE
primeng.org/paginator multiple console errors

### ISSUE THREAD

**Issue by avytak** [primefaces/primeng#14037]
### Describe the bug

When I want to access the https://primeng.org/paginator, I receive multiple errors in the console:
<img width="1676" alt="image" src="https://github.com/primefaces/primeng/assets/108807758/009d8d8b-9f00-4b03-877f-bb10a2121f8c">

The same behavior when I try to check the API tab for paginator.

main.5b4a27f325c7cbec.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'length')
    at get inputClass [as inputClass] (main.5b4a27f325c7cbec.js:1:375801)
    at gt (main.5b4a27f325c7cbec.js:1:362020)
    at e_.runInContext (main.5b4a27f325c7cbec.js:1:1442471)
    at a_ (main.5b4a27f325c7cbec.js:1:1444720)
    at x_ (main.5b4a27f325c7cbec.js:1:1454253)
    at S_ (main.5b4a27f325c7cbec.js:1:1455457)
    at T_ (main.5b4a27f325c7cbec.js:1:1455290)
    at x_ (main.5b4a27f325c7cbec.js:1:1454538)
    at uf (main.5b4a27f325c7cbec.js:1:1453975)
    at Yp.detectChanges (main.5b4a27f325c7cbec.js:1:1456346)

### Environment

MacOS

### Angular version

Does not related to version

### PrimeNG version

16.7.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.16.0

### Browser(s)

Chrome Version 119.0.6045.105

### Steps to reproduce the behavior

1. Open https://primeng.org/
2. Click "Components"
3. Search for the Paginator component 
4. Try to click API tab

### Expected behavior

The console should not have errors and the user should be able to see API info

**Comment by maruthumj** [comment]
@avytak I'm not able to reproduce the issue with the latest code. can you check please?

**Comment by avytak** [comment]
Issue fixed for v16.7.1
