### ISSUE TITLE
failes to compile aot with angular 2.2.2

### ISSUE THREAD

**Issue by huineng** [primefaces/primeng#1407]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

error compiling aot using angular compiler and compiler cli @ 2.2.2

**Expected behavior**

It compiles just fine with angular/compiler and cli @ 2.2.1

* **Angular version:** 2.2.2

* **PrimeNG version:** 1.0.0

* **Language:**TypeScript module ES6 target ES5

* **Node (for AoT issues):** `node --version` =   6.9.1

Error: Unexpected value 'GrowlModule' imported by the module 'AppModule'
    at /Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:12304:33
    at Array.forEach (native)
    at CompileMetadataResolver._loadNgModuleMetadata (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:12289:51)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:12265:23)
    at addNgModule (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:17275:43)
    at /Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:17286:16
    at Array.forEach (native)
    at _createNgModules (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:17285:28)
    at analyzeNgModules (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:17182:16)
    at analyzeAndValidateNgModules (/Users/guyhuinen/Documents/workspace/io-applications2/crr/node_modules/@angular/compiler/bundles/compiler.umd.js:17186:20)

**Comment by huineng** [comment]
working again with 2.2.3
