### ISSUE TITLE
Table - Selection with keyboard brings different errors

### ISSUE THREAD

**Issue by quentin-ineat-ca** [primefaces/primeng#14463]
### Describe the bug

Hello,

Inside Table Component, when the keyboard is used to select rows and according to the section Accessibility [https://primeng.org/table#accessibility](https://primeng.org/table#accessibility), errors are raised or the behavior is not good. Sorry if double bug in one issue, not sure if totally related.

**First bug :** 
Using **control + a** or **shift + space** brings : 
```
ERROR TypeError: _data.slice is not a function
    at Table.dataToRender (vendor.js:205565:20)
    at SelectableRow.onSpaceKey (vendor.js:208571:28)
    at SelectableRow.onKeyDown (vendor.js:208497:14)
    at SelectableRow_keydown_HostBindingHandler (vendor.js:208639:22)
    at executeListenerWithErrorHandling (vendor.js:89768:12)
    at wrapListenerIn_markDirtyAndPreventDefault (vendor.js:89799:18)
    at HTMLTableRowElement.<anonymous> (vendor.js:110025:112)
    at _ZoneDelegate.invokeTask (polyfills.js:8271:171)
    at vendor.js:79809:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (vendor.js:79809:30)
```

Because in table.ts, **data** received is a number with keyboard controls while it's undefined on simple click (or an array of rowData with this.processedData)
```
dataToRender(data: any) {
        const _data = data || this.processedData;
```

**Second bug :** 
fixed in 17.3.1 (updated stackblitz link)
FIX: Multiple selection with SHIFT/click by @vinnyab28 in https://github.com/primefaces/primeng/pull/14209
~~Select row, change page and use **shift** and use **shift** on another row brings a strange behavior by selecting undefined rows. Continue with **shift** and it will select other undefined rows (no error).~~
![Screenshot 2024-01-02 at 16 14 46](https://github.com/primefaces/primeng/assets/110048454/30846661-8f5a-4a3b-9c42-4a138fffe060)

Thank you

### Environment

Chrome 120
MacBook Pro 14.2.1

### Reproducer

https://stackblitz.com/edit/ty2zuu-6efrnz?file=package.json

### Angular version

17.0.5

### PrimeNG version

17.3.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.18.0

### Browser(s)

Chrome 120

### Steps to reproduce the behavior

**First bug :** 
Use **control + a** or **shift + space** (maybe other)
=> Error in console

**Second bug :** 
~~Select row 1 (or other) on page 1
Change Page
Select row 3 (or other) on page 2 with "Shift + click"
Select row 5 (or other) on page 2 with "Shift + click"
=> Undefined rows selected~~

### Expected behavior

**First bug :** 
=> No error

**Second bug :** 
~~=> Corrected rows should be selected~~

**Comment by quentin-ineat-ca** [comment]
Seems the 2nd bug was fixed in 17.3.1
FIX: Multiple selection with SHIFT/click by @vinnyab28 in https://github.com/primefaces/primeng/pull/14209

First bug is still here.
