### ISSUE TITLE
Component: MeterGroup: "Standard Angular field decorators are not supported in JIT mode."

### ISSUE THREAD

**Issue by joshuahills** [primefaces/primeng#15305]
### Describe the bug

When using a MeterGroup component this error appears in the console:
```txt
chunk-C37TKYMN.js:7 ERROR Error: Standard Angular field decorators are not supported in JIT mode.
    at e.u [as container] (chunk-C37TKYMN.js:3:26235)
    at $s.effectFn (chunk-5QU3QOS7.js:1:5192)
    at $s.runEffect (chunk-C37TKYMN.js:7:117686)
    at Object.fn (chunk-C37TKYMN.js:7:117570)
    at Object.a [as run] (chunk-C37TKYMN.js:1:4685)
    at $s.run (chunk-C37TKYMN.js:7:117784)
    at Bs.flushQueue (chunk-C37TKYMN.js:7:117435)
    at chunk-C37TKYMN.js:7:117352
    at k.invoke (polyfills-RT5I6R6G.js:1:6434)
    at Object.onInvoke (chunk-C37TKYMN.js:7:60156)
```
This is also the case for your [documentation site](https://primeng.org/metergroup)

### Environment

Angular version: 17.3.4
PrimeNG version: 17.13.0

### Reproducer

https://stackblitz.com/edit/github-n15q4x?file=src%2Fapp%2Fapp.component.ts

### Angular version

17.3.4

### PrimeNG version

17.13.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.9.0

### Steps to reproduce the behavior

1) Open StackBlitz reproduction or PrimeNG documentation ([https://primeng.org/metergroup](https://primeng.org/metergroup))
2) Open browser console
3) Observe error

**Comment by joshuahills** [comment]
Looks like this has been fixed in [4c7e151](https://github.com/primefaces/primeng/commit/4c7e151f8d9d217c75ac4f71d47433e3dba3090c) so I will close this.
