### ISSUE TITLE
Calendar: rselectionMode range + showTime doesn't work together

### ISSUE THREAD

**Issue by Emiliorth** [primefaces/primeng#15655]
### Describe the bug

p-calendar with selectionMode="range" and [showTime]="true" gives error, when clicking arrows that changes hours
![image](https://github.com/primefaces/primeng/assets/46076240/f31acc47-27f5-47b7-a2a1-2f0770f0d748)

### Environment

Windows 10 Angular 17, PrimeNG 17.17.0

### Angular version

17.3.0

### PrimeNG version

17.17.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

21.6.0

### Browser(s)

Chrome

### Steps to reproduce the behavior
Click on arrow that changes hours
`  <p-calendar [formControlName]="controlName"
                        [inputId]="finalInputId"
                        appendTo="body"
                        [dateFormat]="'dd-mm-yy'"
                        [showIcon]="true"
                        [showClear]="true"
                        [showButtonBar]="true"
                        [showTime]="true"
                        [minDate]="min"
                        [maxDate]="max"
                        selectionMode="range"
                        [required]="requiredAutoForValidation">
                <ng-template pTemplate="triggericon">
                    <app-google-icon [icon]="GoogleIcon.CALENDAR_TODAY"></app-google-icon>
                </ng-template>
            </p-calendar>`

**Comment by matteobertozzi** [comment]
Same problem with 18.0.0-rc.2 and 17.18.12
```
ERROR TypeError: value.toDateString is not a function
    at _Calendar.toggleAMPMIfNotMinDate (primeng-calendar.mjs:3895:43)
    at _Calendar.incrementHour (primeng-calendar.mjs:3889:10)
    at _Calendar.repeat (primeng-calendar.mjs:3930:35)
    at _Calendar.onTimePickerElementMouseDown (primeng-calendar.mjs:3905:12)
    at Calendar_div_3_div_5_Template_p_button_mousedown_2_listener (primeng-calendar.mjs:1576:36)
    at executeListenerWithErrorHandling (core.mjs:25797:12)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:25829:18)
    at HTMLElement.<anonymous> (platform-browser.mjs:745:112)
    at _ZoneDelegate.invokeTask (zone.js:402:33)
    at core.mjs:6717:49
```

```
<p-calendar [(ngModel)]="rangeDates" selectionMode="range"
  [readonlyInput]="true" inputId="range" [showTime]="true" />
```

**Comment by miladFaghihiEdiven** [comment]
Is there any progress?
This bug still exists in v19.0.5.

**Comment by alonewarrior** [comment]
I'm also seeing this bug in v19.0.6.

**Comment by stajne** [comment]
this also happens with p-datepicker

**Comment by stajne** [comment]
The problem is that value is array of dates, not a single date

**Comment by stajne** [comment]
created a fix for this (https://github.com/primefaces/primeng/pull/17781). Since min value can only be checked with the first date of the range, this fix seems simple and correct i hope

**Comment by mitch098** [comment]
Any update on this one?

**Comment by distelka** [comment]
I would like to ask if there is an estimated timeline for fixing the reported bug, as it is critical for our organization and is currently affecting our operations. We would appreciate any update on the progress or expected resolution date.
Thank you in advance for your support and prompt attention.

**Comment by Ricardo-Oporto** [comment]
also waiting on a fix for this

**Comment by Emkacf** [comment]
Are there any plans to fix this in V19? We needed to remove time selector from datepicker in our application but it's affecting the business.

**Comment by jhonatan-medeiros** [comment]
Any update ?

**Comment by mitch098** [comment]
still happening in v20.0.1

**Comment by cagataycivici** [comment]
Tracked at 18479

**Comment by mitch098** [comment]
Still happening in 20.2.0

<img width="722" height="234" alt="Image" src="https://github.com/user-attachments/assets/3f5b5166-4843-4e09-bf16-8f18471921a0" />

**Comment by mitch098** [comment]
This has been an issue since May 2024, can we get some traction on this please?

Started here: https://github.com/primefaces/primeng/issues/15655

**Comment by ud4y-sc** [comment]
We have the same issue but cannot wait for a release. So I have created a directive to fix it for time being. If anyone is facing the same issue please use the directive below.

```ts
import { Directive } from '@angular/core';
import { DatePicker } from 'primeng/datepicker';

type DatePickerPatchedState = DatePicker & {
  datepickerAmPmPatchApplied?: boolean;
};

const noonHour = 12;

@Directive({
  selector:
    'p-datepicker[datepickerAmPmPatch], p-datePicker[datepickerAmPmPatch], p-date-picker[datepickerAmPmPatch]',
  standalone: true
})
export class DatepickerAmPmPatchDirective {
  constructor(private readonly _datePicker: DatePicker) {
    this._applyPatch();
  }

  private _applyPatch(): void {
    const component = this._datePicker as DatePickerPatchedState;

    if (component.datepickerAmPmPatchApplied) {
      return;
    }

    component.datepickerAmPmPatchApplied = true;

    component.toggleAMPMIfNotMinDate = function patchedToggleAMPMIfNotMinDate(
      this: DatePicker,
      newPM: boolean
    ): void {
      const comparableDate = resolveComparableDate(this);
      const { minDate } = this;
      const isSameDay =
        !!minDate &&
        !!comparableDate &&
        minDate.toDateString() === comparableDate.toDateString();

      if (isSameDay && minDate.getHours() >= noonHour) {
        this.pm = true;
      } else {
        this.pm = newPM;
      }
    };
  }
}

function resolveComparableDate(picker: DatePicker): Date | null {
  const { value } = picker;

  if (picker.isRangeSelection() && Array.isArray(value) && value.length > 0) {
    const [start, end] = value;
    return coerceToDate(end ?? start);
  }

  if (picker.isMultipleSelection() && Array.isArray(value) && value.length > 0) {
    const last = value[value.length - 1];
    return coerceToDate(last);
  }

  return coerceToDate(value);
}

function coerceToDate(candidate: unknown): Date | null {
  if (!candidate) {
    return null;
  }

  if (candidate instanceof Date) {
    return candidate;
  }

  if (typeof candidate === 'string' || typeof candidate === 'number') {
    const parsed = new Date(candidate);
    return Number.isNaN(parsed.getTime()) ? null : parsed;
  }

  return null;
}
```


Usage

`<p-datePicker datepickerAmPmPatch></p-datePicker>`

**Comment by distelka** [comment]
Thank you [ud4y](https://github.com/ud4y) for this solution <3

**Comment by davir85** [comment]
Thank you @ud4y .
I’m adding a piece of code to also fix the annoying issue where the datepicker closes in range mode when selecting the second date (so you don’t have time to select the time). It should be added in the _applyPatch method, immediately after redefining the toggleAMPMIfNotMinDate method:

```
 component.onDateSelect = function patchedDateSelect(
            this: DatePicker,
            event: Event,
            dateMeta: any
        ) {
          // v19 version
          // if (this.disabled || !dateMeta.selectable) {
          // v20+ version
            if (this.$disabled() || !dateMeta.selectable) {
                event.preventDefault();
                return;
            }
            
if (this.isMultipleSelection() && this.isSelected(dateMeta)) {
                this.value = this.value.filter((date: Date, i: number) => {
                    return !this.isDateEquals(date, dateMeta);
                });
                if (this.value.length === 0) {
                    this.value = null;
                }
                this.updateModel(this.value);
            } else {
                if (this.shouldSelectDate(dateMeta)) {
                    this.selectDate(dateMeta);
                }
            }

            if (this.hideOnDateTimeSelect && (this.isSingleSelection() || (this.isRangeSelection() && !this.showTime && this.value[1]))) {
                setTimeout(() => {
                    event.preventDefault();
                    this.hideOverlay();

                    if (this.mask) {
                        this.disableModality();
                    }

                    this.cd.markForCheck();
                }, 150);
            }

            this.updateInputfield();
            event.preventDefault();
        }
```
