### ISSUE TITLE
p-chips - Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by psarno** [primefaces/primeng#15970]
### Describe the bug

When using Chrome's autocomplete feature to fill in a value in the p-chips component, when the component loses focus, the following error occurs:

**TypeError: Cannot read properties of undefined (reading 'match')**

The callstack is:

```
    at _Chips.onKeyDown (main.js:221465:59)
    at Chips_Template_input_keydown_5_listener (main.js:221567:22)
    at executeListenerWithErrorHandling (main.js:27641:12)
    at wrapListenerIn_markDirtyAndPreventDefault (main.js:27657:18)
    at HTMLInputElement.<anonymous> (main.js:39856:113)
    at _ZoneDelegate.invokeTask (polyfills.js:321:171)
    at main.js:21563:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (main.js:21563:30)
    at _ZoneDelegate.invokeTask (polyfills.js:321:54)
    at Object.onInvokeTask (main.js:21734:25)
    at _ZoneDelegate.invokeTask (polyfills.js:321:54)
    at _ZoneImpl.runTask (polyfills.js:131:37)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:392:26)
    at invokeTask (polyfills.js:895:12)
    at globalCallback (polyfills.js:916:21)
```

Offending code seems to be here:

![image](https://github.com/primefaces/primeng/assets/18640860/17063ceb-a1c4-4c4f-81c8-f0b52d7accaf)

![image](https://github.com/primefaces/primeng/assets/18640860/40844dc3-0d83-46c6-a10d-b4cbd2442631)

### Environment

PrimeNG 17.18.3
Angular 17.2.4

### Angular version

17.2.4

### PrimeNG version

17.18.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.11.0

### Steps to reproduce the behavior

1. Have a p-chips control that has a prior form submission value, such that Chrome provides an autocomplete list
2. Select an item from the autocomplete list

Error occurs.

### Expected behavior

Error does not occur.

**Comment by mertsincan** [comment]
Hi,

So sorry for the delayed response! Improvements have been made to many components recently, both in terms of performance and enhancement. Therefore, this improvement may have been developed in another issue ticket without realizing it. You can check this in the documentation. If there is no improvement on this, can you open a new issue so we can include it in our roadmap?

Thanks a lot for your understanding!
Best Regards,
