### ISSUE TITLE
p-fileUpload selecting file when fileLimit set to undefined causes js errors

### ISSUE THREAD

**Issue by majkers** [primefaces/primeng#15988]
### Describe the bug

I have a component build on top of fileUpload but with signal inputs. Filelimit property is done like this:
`fileLimit: InputSignal<number | undefined> = input<number | undefined>();`
and when I don't set it in my component, it passes undefined to primeNg. Then transform does his job and value of fileLimit inside primeNg has null as value:
`@Input({ transform: (value: unknown) => numberAttribute(value, null) }) fileLimit: number | undefined;
`
Then when trying to select file to upload with fileSize limit this functuion is being called:

```
  checkFileLimit(files) {
    this.msgs ??= [];
    const hasExistingValidationMessages = this.msgs.length > 0 && this.fileLimit < files.length;
    if (this.isFileLimitExceeded() || hasExistingValidationMessages) {
      this.msgs.push({
        severity: 'error',
        summary: this.invalidFileLimitMessageSummary.replace('{0}', this.fileLimit.toString()),
        detail: this.invalidFileLimitMessageDetail.replace('{0}', this.fileLimit.toString())
      });
    }
  }
```

And when fileLimit is null, this 
` const hasExistingValidationMessages = this.msgs.length > 0 && this.fileLimit < files.length;
`
is true and I get error in my js console:

```
core.mjs:6531 ERROR TypeError: Cannot read properties of null (reading 'toString')
    at _FileUpload.checkFileLimit (primeng-fileupload.mjs:1312:84)
    at _FileUpload.onFileSelect (primeng-fileupload.mjs:1106:10)
```

IMHO. What is missing in hasExistingValidationMessages  is checking this part:
`this.fileLimit`
like this:
` const hasExistingValidationMessages = this.msgs.length > 0 && this.fileLimit && this.fileLimit < files.length;
`
or transform should be fixed.

### Environment

primeNG 17.8.3

### Angular version

17.3.11

### PrimeNG version

17.8.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.12.2

### Browser(s)

All

### Expected behavior

No js errors in console

**Comment by gregorwinkler** [comment]
I can reproduce the problem and have it as well in my project.

I'm not entirely sure why the following is needed in the first place:
`const hasExistingValidationMessages = this.msgs.length > 0 && this.fileLimit < files.length;` (fileupload.ts:856)
Why is it not sufficient to check just for `this.isFileLimitExceeded()` instead of `(this.isFileLimitExceeded() || hasExistingValidationMessages)`?
