### ISSUE TITLE
Component: p-table p-columnFilter p-multiSelect

### ISSUE THREAD

**Issue by 72pitu** [primefaces/primeng#16132]
### Describe the bug

I am not able to make the code example provided in documentation for p-table p-columnFilter p-multiSelect from version 17.8.6 work.
<th>
                    <p-columnFilter field="representative" matchMode="in" [showMenu]="false">
                        <ng-template pTemplate="filter" let-value let-filter="filterCallback">
                            <p-multiSelect 
                                [(ngModel)]="value" 
                                [options]="representatives" 
                                placeholder="Any" 
                                (onChange)="filter($event.value)" 
                                optionLabel="name">
                                    <ng-template let-option pTemplate="item">
                                        <div class="inline-block vertical-align-middle">
                                            <span class="ml-1 mt-1">{{ option.name }}</span>
                                        </div>
                                    </ng-template>
                            </p-multiSelect>
                        </ng-template>
                    </p-columnFilter>
                </th>

I get following error: Cannot use a non-signal variable 'value' in a two-way binding expression. Template variables are read-only.ngtsc(-99)

When trying single binding [ngModel]="value" error disappear however it is not working as shown in primeNg documentation.
                

### Environment

Windows 10, VSC

### Angular version

17.1

### PrimeNG version

17.18.0

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

20.10.0

### Browser(s)

Edge

**Comment by darcoola** [comment]
I'm facing the same issue, but for me one way data binding `[ngModel]="value"` works just fine. It is yet annoying that example from documentation is not working.

**Comment by 72pitu** [comment]
Hey, thx darcoola for your feedback.
I can confirm it's working with this code for me in a table that has complete data loaded already.
      <p-columnFilter field="part_site" matchMode="in" [showMenu]="false">
          <ng-template pTemplate="filter" let-value let-filter="filterCallback">
              <p-multiSelect
                  [ngModel]="value"
                  [options]="testopt"
                  placeholder="Any" 
                  (onChange)="filter($event.value)"
                  optionLabel="name"
                  optionValue="name"
                  appendTo="body"  
                 >
              </p-multiSelect>
          </ng-template>
      </p-columnFilter>
      
      However this filtering does not work properly in conjunction with lazy loading the data in the table.
      
      Any advice how to properly create or update the issue report?

**Comment by giuditta-marino** [comment]
![Screenshot (328)](https://github.com/user-attachments/assets/9778b014-ddec-43dd-b6ff-687578126fc1)
I am a similar issue. I am using Angular 17. I am using a lazy loading table and this kind of code 
<p-multiSelect
[ngModel]="value"
[options]="testopt"
placeholder="Any"
(onChange)="filter($event.value)"
optionLabel="name"
optionValue="name"
appendTo="body"
>

gives me the error:

polyfills-4R6E2C5Q.js:1 ERROR 
TypeError: (this.modelValue(...) || []).some is not a function
    at _MultiSelect.isSelected (primeng-multiselect.mjs:2184:38)
    at primeng-multiselect.mjs:2613:210
    at Array.every (<anonymous>)
    at _MultiSelect.allSelected (primeng-multiselect.mjs:2613:126)
    at MultiSelect_ng_template_16_div_3_ng_template_4_div_0_Template (primeng-multiselect.mjs:610:38)
    at executeTemplate (core.mjs:11268:9)
    at refreshView (core.mjs:12791:13)
    at detectChangesInView$1 (core.mjs:13015:9)
    at detectChangesInViewIfAttached (core.mjs:12978:5)
    at detectChangesInEmbeddedViews (core.mjs:12935:13)

**Comment by RobersonLuo** [comment]
Hi 72pitu，please try this code：
(onChange)="dt.filter($event.value, col.field, 'in')"

 <p-table #dt ....>

**Comment by 72pitu** [comment]
Hi RobersonLuo, thx for your suggestion.

I can confirm that the $event.value and col.field hold correct values when onChange is triggered.
$event.value: ['FI25', 'FI26']
col: part_site


The lazy load event however is missing the values:
filters
part_site: {value: ',', matchMode: 'in'}

**Comment by subhajitneva** [comment]
document should be fixed

**Comment by FabioSimoDev** [comment]
@72pitu 

> [lazy]="true" [lazyLoadOnInit]="true" (onLazyLoad)="lazyLoadEventHandler($event)" The lazy load event however is missing the values when filter is executed: filters part_site: {value: ',', matchMode: 'in'}

How can I fix this? I need to access all the filter values from the Table template, which contains the 'filters' array. If I can't access the filter values, each filter will overwrite the others.

**Comment by bschnabel** [comment]
I had the same problem when using lazy loyding. (still in primeng version 21.1.6)

I could fix it by instead of trying to assign to `value`, assigning to `filterconstraint.value`:

```
                    <p-columnFilter
                      field="myField"
                      display="menu"
                      matchMode="equals"
                      [showMatchModes]="false"
                      [showOperator]="false"
                      [showAddButton]="false"
                    >
                      <ng-template
                        pTemplate="filter"
                        let-filterConstraint="filterConstraint"
                      >
                        <p-select
                          [(ngModel)]="filterConstraint.value"
                          [options]="myOptions"
                          placeholder="Bitte wählen..."
                          [style]="{ width: '300px' }"
                        ></p-select>
                      </ng-template>
                    </p-columnFilter>
```
