### ISSUE TITLE
ViewEncapsulation.ShadowDom / Missing styles

### ISSUE THREAD

**Issue by fxprunayre** [primefaces/primeng#16567]
### Describe the bug

When using 
```ts
  encapsulation: ViewEncapsulation.ShadowDom,
```

![image](https://github.com/user-attachments/assets/b78283fd-7187-412f-807f-6fe4f4ae1fb4)

Styles are added in main body 
![image](https://github.com/user-attachments/assets/56b3fac5-4460-4af9-ac01-9e82d2a1681a)

and are not available in the shadowDOM part.

![image](https://github.com/user-attachments/assets/0cb7424b-32c9-4e2a-960b-20a47a671ac9)

### Environment

-

### Angular version

18.2.0

### PrimeNG version

18.0.0-beta.3

### Build / Runtime

Angular CLI App

### Language

TypeScript

### Node version (for AoT issues node --version)

18.19.1

### Steps to reproduce the behavior

Create a component and use
```ts
  encapsulation: ViewEncapsulation.ShadowDom,
```

### Expected behavior

Insert style in ShadowDom instead of main document.

**Comment by mertsincan** [comment]
I think we can try to inject styles using https://github.com/angular/angular/blob/main/packages/platform-browser/src/dom/dom_renderer.ts#L408

**Comment by fxprunayre** [comment]
> I'll work on it and get back to you.

@mertsincan , I tried to investigate the issue in https://github.com/primefaces/primeng/issues/16567 but being new to primeng it is quite hard to figure out all the mechanism. Any help from a more experimented developer on the theming system would be appreciated! It you can have a look? and check if it is the right direction for a fix. Thanks.

**Comment by maitrungduc1410** [comment]
what I realize is PrimeNG appends CSS to `<head>` at runtime (when a component is actually used)

<img width="480" alt="Image" src="https://github.com/user-attachments/assets/a5fae33e-8b12-48bc-84b7-120ebdb430f3" />

the logic to append CSS is here: [primeng/packages/primeng/src/usestyle/usestyle.ts at master · primefaces/primeng](https://github.com/primefaces/primeng/blob/master/packages/primeng/src/usestyle/usestyle.ts)

I modify the code to append styles to eh shadowRoot, but still some styles are missing:

![Image](https://github.com/user-attachments/assets/83d0d9a5-e655-4b65-b863-587908a20fa6)

Then I found that it's because the style here are under `:root`, while if it's inside ShadowDOM it should be `:host`, then I manually change, then it finally works:

![Image](https://github.com/user-attachments/assets/b8b770e9-ddfc-4868-a9bf-b1c2219f8dee)

---

after spent a whole day looking around primeNG source, I found that the code is deeply couple with real DOM, which is quite hard to decouple it.

Previously, with version <= 17, it uses css in theme files, but from V18 it changed to use `styled mode` (https://primeng.org/guides/migration), which is quite hard to manipulate to support ShadowDOM at runtime at the moment

Hope to see some progress on this in the future

**Comment by Zukqurnain** [comment]
@mertsincan any idea or estimate we can support this shadow dom feature?

**Comment by cagataycivici** [comment]
No plans to support Shadow Dom at the moment due to other tasks with higher priorities and workload.

**Comment by SUSHEELsikarwar** [comment]
✅ Workaround for PrimeNG v19 + Shadow DOM Integration

If you're using ViewEncapsulation.ShadowDom with Angular and PrimeNG 19, PrimeNG themes do not load automatically inside the Shadow DOM due to style encapsulation. This leads to missing component styles.

💡 Solution
Inject PrimeNG styles into the ShadowRoot manually by:

Detecting the dynamically injected PrimeNG <style> tags in <head> (those with data-primeng-style-id).

Cloning them into your Shadow DOM, while replacing :root with :host (so CSS variables still work).

(Optional) Using a MutationObserver to automatically pick up styles when they’re injected (usually delayed).

This code you can write in app.component.ts

 ```
ngAfterViewInit(): void {
    this.injectPrimeNGStyles();

    const observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (node instanceof HTMLStyleElement && node.textContent?.includes('--p-primary-color')) {
            this.injectPrimeNGStyles();
            observer.disconnect();
            return;
          }
        }
      }
    });

    observer.observe(document.head, { childList: true });
  }

  private injectPrimeNGStyles(): void {
    const appRoot = document.querySelector('app-root') as HTMLElement | null;
    const shadowRoot = appRoot?.shadowRoot;
    if (!shadowRoot) {
      console.warn('❌ No shadowRoot found on app-root');
      return;
    }

    const primeNgDynamicStyles = Array.from(document.head.querySelectorAll('style[data-primeng-style-id]'));
    const mainThemeStyle = Array.from(document.head.querySelectorAll('style'))
      .find(style => style.textContent?.includes('--p-primary-color'));

    const allStyles = [...primeNgDynamicStyles];
    if (mainThemeStyle) allStyles.push(mainThemeStyle);

    allStyles.forEach(styleEl => {
      if (!styleEl.textContent) return;
      const clonedStyle = document.createElement('style');
      clonedStyle.textContent = styleEl.textContent.replace(/:root/g, ':host');
      shadowRoot.appendChild(clonedStyle);
    });

    console.log('✅ PrimeNG theme and styles injected into Shadow DOM');
  }
```

**Comment by fxprunayre** [comment]
Trying to summarize current status of this with v20

## Style injection to be improved

So indeed, using something like:

```ts
import {Component, ElementRef, inject, OnDestroy, OnInit,} from '@angular/core';

/**
 * Workaround https://github.com/primefaces/primeng/issues/16567
 * Add missing CSS styles in shadow DOM but it still remains issues with popups and overlays
 * Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
 */
@Component({
  selector: 'gc-shadowdomstyle-component',
  template: '<div></div>',
})
export class GcShadowdomstyleComponent implements OnInit, OnDestroy {
  el = inject(ElementRef);

  loadedStyles: string[] = [];

  observer: MutationObserver = {} as MutationObserver;

  ngOnInit(): void {
    this.observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (
            node instanceof HTMLStyleElement &&
            (node.getAttribute('data-primeng-style-id') !== null ||
              node.textContent?.includes('--p-primary-color'))
          ) {
            this.injectPrimeNGStyles();
            return;
          }
        }
      }
    });
    this.observer.observe(document.head, { childList: true });
  }

  ngOnDestroy() {
    this.observer.disconnect();
  }

  private injectPrimeNGStyles(): void {
    const shadowRoot = this.el.nativeElement?.shadowRoot;
    if (!shadowRoot) {
      return;
    }

    const primeNgDynamicStyles = Array.from(
      document.head.querySelectorAll('style[data-primeng-style-id]')
    );
    const mainThemeStyle = Array.from(
      document.head.querySelectorAll('style')
    ).find(style => style.textContent?.includes('--p-primary-color'));
    const allStyles = [...primeNgDynamicStyles];
    if (mainThemeStyle) allStyles.push(mainThemeStyle);

    allStyles.forEach(styleEl => {
      const styleId = styleEl.getAttribute('data-primeng-style-id') || '';
      if (!styleEl.textContent || this.loadedStyles.includes(styleId)) return;
      const clonedStyle = document.createElement('style');
      clonedStyle.type = 'text/css';
      clonedStyle.setAttribute('data-primeng-style-id', styleId);
      clonedStyle.textContent = styleEl.textContent.replace(/:root/g, ':host');
      shadowRoot.appendChild(clonedStyle);

      this.loadedStyles.push(styleId);
    });
  }
}
```
and creating a component
```ts
export class WebComponentTest extends GcShadowdomstyleComponent {
```
can workaround the styling issue. So this explains that components in a shadow DOM should add the styles to the shadow DOM root instead of the document.


## DOM manipulation to be improved

Some components like `p-select` or `p-date-picker` triggers another type of exception when using `window` object

```
ERROR TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at overflowCheck (primeng-dom.mjs:209:65)
```

**Comment by khactrungphamteo** [comment]
> Trying to summarize current status of this with v20
> 
> ## Style injection to be improved
> So indeed, using something like:
> 
> import {Component, ElementRef, inject, OnDestroy, OnInit,} from '@angular/core';
> 
> /**
>  * Workaround https://github.com/primefaces/primeng/issues/16567
>  * Add missing CSS styles in shadow DOM but it still remains issues with popups and overlays
>  * Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
>  */
> @Component({
>   selector: 'gc-shadowdomstyle-component',
>   template: '<div></div>',
> })
> export class GcShadowdomstyleComponent implements OnInit, OnDestroy {
>   el = inject(ElementRef);
> 
>   loadedStyles: string[] = [];
> 
>   observer: MutationObserver = {} as MutationObserver;
> 
>   ngOnInit(): void {
>     this.observer = new MutationObserver(mutations => {
>       for (const mutation of mutations) {
>         for (const node of Array.from(mutation.addedNodes)) {
>           if (
>             node instanceof HTMLStyleElement &&
>             (node.getAttribute('data-primeng-style-id') !== null ||
>               node.textContent?.includes('--p-primary-color'))
>           ) {
>             this.injectPrimeNGStyles();
>             return;
>           }
>         }
>       }
>     });
>     this.observer.observe(document.head, { childList: true });
>   }
> 
>   ngOnDestroy() {
>     this.observer.disconnect();
>   }
> 
>   private injectPrimeNGStyles(): void {
>     const shadowRoot = this.el.nativeElement?.shadowRoot;
>     if (!shadowRoot) {
>       return;
>     }
> 
>     const primeNgDynamicStyles = Array.from(
>       document.head.querySelectorAll('style[data-primeng-style-id]')
>     );
>     const mainThemeStyle = Array.from(
>       document.head.querySelectorAll('style')
>     ).find(style => style.textContent?.includes('--p-primary-color'));
>     const allStyles = [...primeNgDynamicStyles];
>     if (mainThemeStyle) allStyles.push(mainThemeStyle);
> 
>     allStyles.forEach(styleEl => {
>       const styleId = styleEl.getAttribute('data-primeng-style-id') || '';
>       if (!styleEl.textContent || this.loadedStyles.includes(styleId)) return;
>       const clonedStyle = document.createElement('style');
>       clonedStyle.type = 'text/css';
>       clonedStyle.setAttribute('data-primeng-style-id', styleId);
>       clonedStyle.textContent = styleEl.textContent.replace(/:root/g, ':host');
>       shadowRoot.appendChild(clonedStyle);
> 
>       this.loadedStyles.push(styleId);
>     });
>   }
> }
> and creating a component
> 
> export class WebComponentTest extends GcShadowdomstyleComponent {
> can workaround the styling issue. So this explains that components in a shadow DOM should add the styles to the shadow DOM root instead of the document.
> 
> ## DOM manipulation to be improved
> Some components like `p-select` or `p-date-picker` triggers another type of exception when using `window` object
> 
> ```
> ERROR TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
>     at overflowCheck (primeng-dom.mjs:209:65)
> ```

@fxprunayre this works, you are life saver

**Comment by mariovyord** [comment]
Hi, @fxprunayre and @mertsincan, I have been working on patch to allow for PrimeNG usage in ShadowDOM. You can check it out [here in this PR](https://github.com/primefaces/primeng/pull/19545). 

So far in my testing it works without major issues. 

My plan is to create a patch with [patch-package](https://www.npmjs.com/package/patch-package) library and use it in a micro-frontend setup where different PrimeNG versions need to co-exist. The only thing I'm missing so far is to come up with an easy way to provide the shadowRoot to PrimeNG, but this looks like the easiest task from the bunch. 

It is to be used like this:

```
providePrimeNG({
  theme: { preset: Aura },
  styleContainer: shadowRoot,
  overlayAppendTo: shadowRoot
});
```

EDIT:
pnpm patch for anyone interested: https://gist.github.com/mariovyord/2620080f4b9f08290940a7609000feaf

**Comment by cetincakiroglu** [comment]
Hi,

This issue has been fixed in PrimeNG v22.
