### ISSUE TITLE
Calendar ehancement : support of  ISO 8601 date

### ISSUE THREAD

**Issue by rlouissidney** [primefaces/primeng#1895]
Hello,

Is it possible to have an option to support ISO Date via the ISO 8601 format ?
Perhaps have a separate presentation format and input value format ?  

I use a lot of webservice with JSON data and the ISO 8601 seems to be a standard.

Thanks !

**Comment by blinkxzero** [comment]
This issue is actually breaking my application. 

I need the input to be formatted as an ISO string for my database (JSON), but the p-calendar input only accepts Date types or it throws an exception.

**Comment by jneveux** [comment]
Below is a test on my side (version 2.0.0). 

Date coming from the server REST end point:
`{"dateOne":"2017-03-01T10:45:09.230Z"}`
Calendar configuration:
`<p-calendar dateFormat="dd/mm/yy" [(ngModel)]="dateObjectTwo.dateOne" ></p-calendar>`
Stacktrace:
`Date type string
error_handler.js:54EXCEPTION: Uncaught (in promise): Unexpected literal at position 2ErrorHandler.handleError @ error_handler.js:54next @ application_ref.js:348schedulerFn @ async.js:93SafeSubscriber.__tryOrUnsub @ Subscriber.js:234SafeSubscriber.next @ Subscriber.js:183Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:79NgZone.triggerError @ ng_zone.js:333onHandleError @ ng_zone.js:294ZoneDelegate.handleError @ zone.js:334Zone.runGuarded @ zone.js:142_loop_1 @ zone.js:540drainMicroTaskQueue @ zone.js:549ZoneTask.invoke @ zone.js:420
error_handler.js:59ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:59next @ application_ref.js:348schedulerFn @ async.js:93SafeSubscriber.__tryOrUnsub @ Subscriber.js:234SafeSubscriber.next @ Subscriber.js:183Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:79NgZone.triggerError @ ng_zone.js:333onHandleError @ ng_zone.js:294ZoneDelegate.handleError @ zone.js:334Zone.runGuarded @ zone.js:142_loop_1 @ zone.js:540drainMicroTaskQueue @ zone.js:549ZoneTask.invoke @ zone.js:420
error_handler.js:60Error: Uncaught (in promise): Unexpected literal at position 2
    at new Error (native)
    at resolvePromise (http://localhost:4200/vendor.bundle.js:129018:31) [angular]
    at http://localhost:4200/vendor.bundle.js:129057:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:33920:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:128737:36) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:128541:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:128904:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:128795:25) [<root>]ErrorHandler.handleError @ error_handler.js:60next @ application_ref.js:348schedulerFn @ async.js:93SafeSubscriber.__tryOrUnsub @ Subscriber.js:234SafeSubscriber.next @ Subscriber.js:183Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:79NgZone.triggerError @ ng_zone.js:333onHandleError @ ng_zone.js:294ZoneDelegate.handleError @ zone.js:334Zone.runGuarded @ zone.js:142_loop_1 @ zone.js:540drainMicroTaskQueue @ zone.js:549ZoneTask.invoke @ zone.js:420
zone.js:516Unhandled Promise rejection: Unexpected literal at position 2 ; Zone: angular ; Task: Promise.then ; Value: Unexpected literal at position 2 undefinedconsoleError @ zone.js:516_loop_1 @ zone.js:545drainMicroTaskQueue @ zone.js:549ZoneTask.invoke @ zone.js:420
zone.js:518ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Unexpected literal at position 2
    at new Error (native)
    at reso…, rejection: "Unexpected literal at position 2", promise: ZoneAwarePromise, zone: Zone, task: ZoneTask…}__zone_symbol__error: Error: Uncaught (in promise): Unexpected literal at position 2
    at new Error (native)
    at resolvePromise (http://localhost:4200/vendor.bundle.js:129018:31) [angular]
    at http://localhost:4200/vendor.bundle.js:129057:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:33920:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:128737:36) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:128541:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:128904:35) [<root>]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:128795:25) [<root>]__zone_symbol__message: "Uncaught (in promise): Unexpected literal at position 2"__zone_symbol__stack: "Error: Uncaught (in promise): Unexpected literal at position 2↵    at new Error (native)↵    at resolvePromise (http://localhost:4200/vendor.bundle.js:129018:31) [angular]↵    at http://localhost:4200/vendor.bundle.js:129057:17 [angular]↵    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:33920:37) [angular]↵    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:128737:36) [angular]↵    at Zone.runTask (http://localhost:4200/vendor.bundle.js:128541:47) [<root> => angular]↵    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:128904:35) [<root>]↵    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:128795:25) [<root>]"message: (...)get message: ()set message: (value)name: (...)get name: ()set name: (value)originalStack: (...)get originalStack: ()set originalStack: (value)promise: ZoneAwarePromiserejection: "Unexpected literal at position 2"stack: (...)get stack: ()set stack: (value)task: ZoneTasktoSource: ()toString: ()zone: ZonezoneAwareStack: (...)get zoneAwareStack: ()set zoneAwareStack: (value)__proto__: ObjectconsoleError @ zone.js:518_loop_1 @ zone.js:545drainMicroTaskQueue @ zone.js:549ZoneTask.invoke @ zone.js:420`

**Comment by rlouissidney** [comment]
A 'simple' workaround could be found here : 
https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates
See for using : https://github.com/RickStrahl/json.date-extensions 
But I still think the support of iso8601 date is a nice feature.

**Comment by cagataycivici** [comment]
This should be fixed in recent PrimeNG release, please try with it and if the issue persists drop a comment with along with a test case based on plunkr below and we'll review again.

http://plnkr.co/edit/Wj39h1?p=preview

**Comment by rlouissidney** [comment]
Thanks !  I made a demo here : http://plnkr.co/edit/ElnS7HLuLUahTpXbICB4?p=preview
It seems difficult to the calendar to deal with iso date.
Note the code in my previous links above is very interesting ;) the function "dateStringToDate" could decode with a regular expression ISO date and MS date automatically ;) Not need to add new input options, a little improvement of pr 3098 which is a good start.

**Comment by jimbo74** [comment]
this should be reopened as it is still an issue

**Comment by stevie6410** [comment]
+1 Still having the same issue with v4.1.1

The demo produced by @rlouissidney is exactly this issue I am having.

**Comment by thecml** [comment]
Had the same issue with 4.2.2. Solved it by converting the date I was binding using toLocaleDateString(). A bit of a workaround though.

**Comment by parth23** [comment]
@thecml Could you tell me in detail how you did that?

**Comment by thecml** [comment]
Basically just converting my dates to strings in a certain format such as "Dec 25, 1995" before doing the data binding, instead of directly binding the Date properties.

**Comment by szanellato93** [comment]
still have the issue with "primeng": "^4.3.0-rc.2". Can be resolve with new Date(value)

**Comment by ronbuchanan** [comment]
Any updates to this?

**Comment by Mynken** [comment]
This solution helped me:
dateVariable = new Date(dateVariable );
Just try parse your date again to Date.

**Comment by KubaJakubowski** [comment]
Unfortunately this issue still exist in primeng 10^.
Please be aware that even if it's possible to easily convert iso string to date and date to iso string, it still would be neat feature because it would be easier to quickly bind data between front and back
