### ISSUE TITLE
[Bug] Datatable resizableColumns jquery error

### ISSUE THREAD

**Issue by Luchillo** [primefaces/primeng#224]
I have this setup:
```html
<h3>{{ widget.title }}</h3>
<p-dataTable [value]="widget.tableData" 
        [lazy]="widget.item_config.tableConfig.paginator || false"
        [rows]="widget.item_config.tableConfig.rows || 10"
        [paginator]="widget.item_config.tableConfig.paginator || false"
        [totalRecords]="widget.data.length"
        resizableColumns="true"
            
        (onLazyLoad)="tablePageChange($event, widget)">

    <p-column *ngFor="#col of widget.item_config.tableConfig.columns" 
              [field]="col.field" 
              [header]="col.header">
    </p-column>

</p-dataTable>
```

However when i add the property `resizableColumns` it gets an error and i'm unable to resize, the table still shows but the error count keeps growing and the resize feature doesn't work:
![screen shot 2016-04-19 at 10 43 46 am](https://cloud.githubusercontent.com/assets/9698639/14645527/a7074bde-061b-11e6-9db0-339c65527d53.png)

**Comment by Mrtcndkn** [comment]
Could you please share your code or a plunker for replicating your issue  because your setup looks fine and locally there was no error for this kind of usage.

**Comment by Luchillo** [comment]
Is there a basic plunker to start?

**Comment by Mrtcndkn** [comment]
Unfortunately there is none.

**Comment by Luchillo** [comment]
What about the cdn's necesary for dataTable?

**Comment by Luchillo** [comment]
I'm having a probably related issue with the dialog, testing the default one from example gives error, maybe it has to do with i using the ngUpgrade library to use Angular 2 in a A1 project?

**Comment by Mrtcndkn** [comment]
I'll make some research about that how it effecting the current situation and get back to you.

**Comment by Luchillo** [comment]
@Mrtcndkn Ty, btw is there any cdn urls available for primeng? i was going to create a plunkr to replicate the error

**Comment by cagataycivici** [comment]
@Luchillo Not that I know of yet.

Btw, do you have;

`<script src="node_modules/primeui/primeui-ng-all.min.js"></script>`

Resize part uses our resize plugin, that is not converted to native javascript yet.

**Comment by Luchillo** [comment]
I'm redefining my build process right now, i think it was missing, weird thing is that some things worked without that and others not.

**Comment by Luchillo** [comment]
@cagataycivici Can you re-open this again? i have included the file mentioned and now the error is this:
```js
_originalException: Error: cannot call methods on puicolresize prior to initialization; attempted to call method 'destroy' at Function.p.extend.error (http://localhost:50002/js/primeui-ng-all.min.js:1:1813) at HTMLDivElement.<anonymous> (http://localhost:50002/js/primeui-ng-all.min.js:3:27179) at Function.p.extend.each (http://localhost:50002/js/primeui-ng-all.min.js:1:2760) at p.fn.p.each (http://localhost:50002/js/primeui-ng-all.min.js:1:845) at e.fn.(anonymous function) [as puicolresize] (http://localhost:50002/js/primeui-ng-all.min.js:3:26921) at DataTable.ngOnDestroy (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1345:2), <anonymous>:645:55) at AppView._View_DashBoardPage5.destroyInternal (DashBoardPage.template.js:1093:23) at AppView._destroyLocal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:189:14) at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:169:22) at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:160:25)
_originalStack: "Error: cannot call methods on puicolresize prior to initialization; attempted to call method 'destroy'↵    at Function.p.extend.error (http://localhost:50002/js/primeui-ng-all.min.js:1:1813)↵    at HTMLDivElement.<anonymous> (http://localhost:50002/js/primeui-ng-all.min.js:3:27179)↵    at Function.p.extend.each (http://localhost:50002/js/primeui-ng-all.min.js:1:2760)↵    at p.fn.p.each (http://localhost:50002/js/primeui-ng-all.min.js:1:845)↵    at e.fn.(anonymous function) [as puicolresize] (http://localhost:50002/js/primeui-ng-all.min.js:3:26921)↵    at DataTable.ngOnDestroy (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1345:2), <anonymous>:645:55)↵    at AppView._View_DashBoardPage5.destroyInternal (DashBoardPage.template.js:1093:23)↵    at AppView._destroyLocal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:189:14)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:169:22)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:160:25)"
_wrapperMessage: "Error in ./DashBoardPage class DashBoardPage - inline template:51:10"
_wrapperStack: "Error: Error in ./DashBoardPage class DashBoardPage - inline template:51:10↵    at ViewWrappedException.WrappedException [as constructor] (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:31:2), <anonymous>:34:31)↵    at new ViewWrappedException (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:698:2), <anonymous>:59:16)↵    at AppView._rethrowWithContext (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:329:23)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:172:22)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:160:25)↵    at AppView.destroy (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:152:14)↵    at ViewContainerRef_.remove (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:704:2), <anonymous>:131:14)↵    at NgFor._bulkRemove (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:909:2), <anonymous>:156:37)↵    at NgFor._applyChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:909:2), <anonymous>:119:33)↵    at NgFor.ngDoCheck (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:909:2), <anonymous>:105:22)"
context: (...)
message: (...)
originalException: Error: cannot call methods on puicolresize prior to initialization; attempted to call method 'destroy' at Function.p.extend.error (http://localhost:50002/js/primeui-ng-all.min.js:1:1813) at HTMLDivElement.<anonymous> (http://localhost:50002/js/primeui-ng-all.min.js:3:27179) at Function.p.extend.each (http://localhost:50002/js/primeui-ng-all.min.js:1:2760) at p.fn.p.each (http://localhost:50002/js/primeui-ng-all.min.js:1:845) at e.fn.(anonymous function) [as puicolresize] (http://localhost:50002/js/primeui-ng-all.min.js:3:26921) at DataTable.ngOnDestroy (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1345:2), <anonymous>:645:55) at AppView._View_DashBoardPage5.destroyInternal (DashBoardPage.template.js:1093:23) at AppView._destroyLocal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:189:14) at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:169:22) at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:160:25)
originalStack: "Error: cannot call methods on puicolresize prior to initialization; attempted to call method 'destroy'↵    at Function.p.extend.error (http://localhost:50002/js/primeui-ng-all.min.js:1:1813)↵    at HTMLDivElement.<anonymous> (http://localhost:50002/js/primeui-ng-all.min.js:3:27179)↵    at Function.p.extend.each (http://localhost:50002/js/primeui-ng-all.min.js:1:2760)↵    at p.fn.p.each (http://localhost:50002/js/primeui-ng-all.min.js:1:845)↵    at e.fn.(anonymous function) [as puicolresize] (http://localhost:50002/js/primeui-ng-all.min.js:3:26921)↵    at DataTable.ngOnDestroy (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1345:2), <anonymous>:645:55)↵    at AppView._View_DashBoardPage5.destroyInternal (DashBoardPage.template.js:1093:23)↵    at AppView._destroyLocal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:189:14)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:169:22)↵    at AppView._destroyRecurse (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1167:2), <anonymous>:160:25)"
```

**Comment by cagataycivici** [comment]
Reopening, in next version we'll probably implement this as native.

**Comment by Luchillo** [comment]
This link to an issue is the way to go to fix this, relate to this comment: [300#issuecomment-217253716](https://github.com/primefaces/primeng/issues/300#issuecomment-217253716)

**Comment by pantonis** [comment]
+1 Have the same problem here.

**Comment by Luchillo** [comment]
@pantonis Did you test the comment i linked?

**Comment by pantonis** [comment]
@Luchillo  yes I removed jquery and it worked. Hope the bug will be fixed.

Thanks

**Comment by Luchillo** [comment]
It's not quite a bug, just that they made it as a bundle instead of making it a dependency.

**Comment by pantonis** [comment]
Problem now is that I cannot use jquery for other things in the site.

**Comment by Luchillo** [comment]
Why's that? i used mine in an NgUpgrade project with Ng1 and Ng2, all Ng1 code was legacy and Ng2 code is mine and it went perfectly when i replaced the JQuery lib with the PrimeNg bundle.
