### ISSUE TITLE
validator.registerOnValidatorChange is not a function on Calender

### ISSUE THREAD

**Issue by rahuldev761** [primefaces/primeng#2268]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

I am using prime calender  with form and face **validator.registerOnValidatorChange** is not a function  error. If I do not use `formControlName`  its works fine.

```
  this.Form = this._fb.group({
      assigned_lineman: [''],
      priority: ['', [Validators.required]],
      expected_resolution_date: ['2016-01-01'],
      description: ['']
    });
```

```
  <label>Expected Resolution Date *</label>
      <div>
        <p-calendar dateFormat="yy-mm-dd" [showIcon]="true"     formControlName="expected_resolution_date"></p-calendar>
        <span style="margin-left:35px"></span>
      </div>
```
**error**

```
error_handler.js:46 EXCEPTION: Error in ./EditComplaints class EditComplaints - inline template:0:6 caused by: validator.registerOnValidatorChange is not a functionErrorHandler.handleError @ error_handler.js:46next @ application_ref.js:291schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:73NgZone.runGuarded @ ng_zone.js:239outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
error_handler.js:48 ORIGINAL EXCEPTION: validator.registerOnValidatorChange is not a functionErrorHandler.handleError @ error_handler.js:48next @ application_ref.js:291schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:73NgZone.runGuarded @ ng_zone.js:239outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
error_handler.js:51 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:51next @ application_ref.js:291schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:236Zone.runGuarded @ zone.js:131NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:73NgZone.runGuarded @ ng_zone.js:239outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:265Zone.runTask @ zone.js:154ZoneTask.invoke @ zone.js:335
error_handler.js:52 TypeError: validator.registerOnValidatorChange is not a function
    at http://localhost:8000/vendor.bundle.js:38993:72
    at Array.forEach (native)
    at cleanUpControl (http://localhost:8000/vendor.bundle.js:38993:24)
    at http://localhost:8000/vendor.bundle.js:38213:103
    at Array.forEach (native)
    at FormGroupDirective._updateDomValue (http://localhost:8000/vendor.bundle.js:38210:25)
    at FormGroupDirective.ngOnChanges (http://localhost:8000/vendor.bundle.js:38145:18)
    at _View_EditComplaints0.detectChangesInternal (EditComplaints.ngfactory.js:835:58)
    at _View_EditComplaints0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_EditComplaints0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_ComplaintsList0.AppView.detectViewChildrenChanges (http://localhost:8000/vendor.bundle.js:33016:19)
    at _View_ComplaintsList0.detectChangesInternal (ComplaintsList.ngfactory.js:1387:8)
    at _View_ComplaintsList0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_ComplaintsList0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_ComplaintsList_Host0.AppView.detectViewChildrenChanges (http://localhost:8000/vendor.bundle.js:33016:19)
    at _View_ComplaintsList_Host0.detectChangesInternal (ComplaintsList_Host.ngfactory.js:46:8)
    at _View_ComplaintsList_Host0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_ComplaintsList_Host0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_Complaints0.AppView.detectContentChildrenChanges (http://localhost:8000/vendor.bundle.js:33008:19)
    at _View_Complaints0.AppView.detectChangesInternal (http://localhost:8000/vendor.bundle.js:33000:14)
    at _View_Complaints0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_Complaints0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_Complaints_Host0.AppView.detectViewChildrenChanges (http://localhost:8000/vendor.bundle.js:33016:19)
    at _View_Complaints_Host0.AppView.detectChangesInternal (http://localhost:8000/vendor.bundle.js:33001:14)
    at _View_Complaints_Host0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_Complaints_Host0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_Pages0.AppView.detectContentChildrenChanges (http://localhost:8000/vendor.bundle.js:33008:19)
    at _View_Pages0.detectChangesInternal (Pages.ngfactory.js:240:8)
    at _View_Pages0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_Pages0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_Pages_Host0.AppView.detectViewChildrenChanges (http://localhost:8000/vendor.bundle.js:33016:19)
    at _View_Pages_Host0.detectChangesInternal (Pages_Host.ngfactory.js:31:8)
    at _View_Pages_Host0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_Pages_Host0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_App0.AppView.detectContentChildrenChanges (http://localhost:8000/vendor.bundle.js:33008:19)
    at _View_App0.detectChangesInternal (App.ngfactory.js:81:8)
    at _View_App0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_App0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at _View_App_Host0.AppView.detectViewChildrenChanges (http://localhost:8000/vendor.bundle.js:33016:19)
    at _View_App_Host0.detectChangesInternal (App_Host.ngfactory.js:36:8)
    at _View_App_Host0.AppView.detectChanges (http://localhost:8000/vendor.bundle.js:32990:14)
    at _View_App_Host0.DebugAppView.detectChanges (http://localhost:8000/vendor.bundle.js:33095:44)
    at ViewRef_.detectChanges (http://localhost:8000/vendor.bundle.js:33481:20)
    at http://localhost:8000/vendor.bundle.js:26236:84
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:8000/vendor.bundle.js:26236:38)
    at http://localhost:8000/vendor.bundle.js:26177:105
    at ZoneDelegate.invoke (http://localhost:8000/polyfills.bundle.js:15211:26)
    at Object.onInvoke (http://localhost:8000/vendor.bundle.js:36136:37)
    at ZoneDelegate.invoke (http://localhost:8000/polyfills.bundle.js:15210:32)
    at Zone.run (http://localhost:8000/polyfills.bundle.js:15093:43)
    at NgZoneImpl.runInner (http://localhost:8000/vendor.bundle.js:36163:71)
    at NgZone.run (http://localhost:8000/vendor.bundle.js:36064:66)
    at Object.next (http://localhost:8000/vendor.bundle.js:26177:81)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8000/vendor.bundle.js:30467:70)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8000/vendor.bundle.js:85589:16)
    at SafeSubscriber.next (http://localhost:8000/vendor.bundle.js:85538:22)
    at Subscriber._next (http://localhost:8000/vendor.bundle.js:85491:26)
    at Subscriber.next (http://localhost:8000/vendor.bundle.js:85455:18)
    at EventEmitter.Subject.next (http://localhost:8000/vendor.bundle.js:85207:25)
    at EventEmitter.emit (http://localhost:8000/vendor.bundle.js:30459:76)
    at NgZone._checkStable (http://localhost:8000/vendor.bundle.js:35974:44)
    at NgZoneImpl.onLeave (http://localhost:8000/vendor.bundle.js:35946:23)
    at Object.onInvoke (http://localhost:8000/vendor.bundle.js:36139:27)
    at ZoneDelegate.invoke (http://localhost:8000/polyfills.bundle.js:15210:32)
    at Zone.runGuarded (http://localhost:8000/polyfills.bundle.js:15107:47)
    at NgZoneImpl.runInnerGuarded (http://localhost:8000/vendor.bundle.js:36165:78)
    at NgZone.runGuarded (http://localhost:8000/vendor.bundle.js:36069:73)
    at HTMLAnchorElement.outsideHandler (http://localhost:8000/vendor.bundle.js:47111:79)
    at ZoneDelegate.invokeTask (http://localhost:8000/polyfills.bundle.js:15244:35)
    at Zone.runTask (http://localhost:8000/polyfills.bundle.js:15133:47)
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost:8000/polyfills.bundle.js:15314:33)
```

**Comment by sergw** [comment]
This is probably Angular bug. See here: https://github.com/angular/angular/pull/12593

**Comment by cagataycivici** [comment]
Seems like an Angular bug.
