### ISSUE TITLE
Error: XHR Error 'primeng/primeng' 404 not found

### ISSUE THREAD

**Issue by xFailsafeNY** [primefaces/primeng#228]
Getting a problem while trying to include this in my project:

Error:
`angular2-polyfills.js:390 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/primeng/primeng
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:830:30)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:423:38)
	    at Zone.runTask (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:320:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:490:34)
	Error loading http://localhost:3000/node_modules/primeng/primeng as "primeng/primeng" from http://localhost:3000/app/js/components/Dashboard.js`

index.html:

```html
<script>
    System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        },
        map: {
          'primeng': "node_modules/primeng"
        }
      });
      System.import('app/js/components/main')
            .then(null, console.error.bind(console));
  </script>
```

Dashboard.js:

```typescript
import {DataTable} from 'primeng/primeng';
```

**Comment by xFailsafeNY** [comment]
Might of fixed it with:

```javascript
System.config({     
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          'node_modules/primeng': {
            format: 'cjs',
            defaultExtension: 'js'
          }
         },
         map: {
          "primeng": "node_modules/primeng"
        }
      });
      System.import('app/js/components/main')
            .then(null, console.error.bind(console));
```
