### ISSUE TITLE
Angular throw error adding o-dropdown to dom

### ISSUE THREAD

**Issue by bluethefish** [primefaces/primeng#2354]
[x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Adding simple drop down list

**Expected behavior**
No parsing exception

**Minimal reproduction of the problem with instructions**
Error in event handler for (unknown): SyntaxError: Failed to execute 'addRule' on 'CSSStyleSheet': Failed to parse the rule '::content #block-openads-13, ::content #bottom_sponsored_links, ::content #circad_wrapper, ::content #content_right_ad, ::content #ctl00_topAd, ::content #dfp-ad-top, ::content #dlads, ::content #floatads, ::content #gameSquareAd, ::content #gpt-ad-halfpage, ::content #headeradbox, ::content #iframe_ad_2, ::content #leftframeAD, ::content #medrec_top_ad, ::content #my-adsLREC2, ::content #page_ad, ::content #rightBoxAdvertisementLast, ::content #searchAdSkyscraperBox, ::content #sidebar-post-120x120-banner, ::content #specialadfeatures, ::content #squareAd, ::content #themis-ads, ::content #top_span_ad, ::content #video-in-player-ad, ::content #yahooAdsBottom, ::content .AdPanel, ::content .FlatAds, ::content .SidebarMiddleAdContainer, ::content .ad-160, ::content .ad-block-bottom, ::content .ad-header-container, ::content .ad-notice, ::content .ad-spot, ::content .ad1_bottom, ::content .adArticleBanner, ::content .adHorisontal, ::content .adSpot-twin, ::content .ad_954-60, ::content .ad_feature, ::content .ad_pic, ::content .adds620x90, ::content .adpost, ::content .ads-player-03, ::content .adsHeading, ::content .ads_qc1, ::content .adsense728, ::content .adsplat, ::content .adv250, ::content .advert-center, ::content .advertis-left, ::content .advertisesingle, ::content .adzone-sidebar, ::content .articlepage_ads_top, ::content .banner_300_250, ::content .block-ads1, ::content .bottom-ad-large, ::content .breakingNewsModuleSponsor, ::content .cl-ad-slot-post2, ::content .content-header-ad, ::content .dynamic_adslot, ::content .follower-ad-bottom, ::content .galleria-AdOverlay, ::content .googleAd_160x600, ::content .hbox_top_sponsor, ::content .homeCentreAd, ::content .images-adv, ::content .jalbum-ad-container, ::content .leaderboard_ad, ::content .macad, ::content .middle-ads, ::content .mpu-wrapper, ::content .nomobilead, ::content .pan-ad-sidebar1, ::content .pos_advert, ::content .rail-article-sponsored, ::content .right-rail-ad, ::content .rtmad, ::content .side-ad-big, ::content .simplead-container, ::content .splitAd, ::content .sponsoredLinksHeader, ::content .story_ads_right_spl_budget, ::content .text_ad_title, ::content .topAdLeft, ::content .twoadcolr, ::content .wahAd, ::content .widget_vb_sidebar_ad, ::content a[href^="http://install.securewebsiteaccess.com/"], ::content a[href^="http://www.tirerack.com/affiliates/"], ::content #main_col > #center_col div[style="font-size:14px;margin:0 4px;padding:1px 5px;background:#fff7ed"], ::content .c-ad, ::content .c-ad-size2, ::content .c-ad-size3, ::content #desktop-unrec-ad, ::content a[href^="https://understandsolar.com/signup/?lead_source="][href*=&tracking_code="], ::content .ad_stream, ::content #adserver_HeaderAd, ::content .header-ad-frame, ::content .m-in-content-ad--slot, ::content a[href^="https://understandsolar.com/signup/?lead_source="][href*="&tracking_code="], ::content .m-header-ad, ::content .m-in-content-ad-row, ::content .m-sidebar-ad, ::content .m-header-ad--slot, ::content .m-in-content-ad-row--bonus, ::content .m-sidebar-ad--slot, ::content .m-in-content-ad, ::content #article-advert-dfp, ::content #ads1_sidebar, ::content .article-advert-dfp, ::content .reklam_mgid, ::content .ads1_sidebar, ::content .abp_ob_wl, ::content #ad-728, ::content #cmn_ad_tag_head, ::content .ad-2, ::content .ad-border, ::content .ads-section, ::content .contentAds, ::content .s_ad_300x250, ::content .singleAd, ::content .textads, ::content #BannerAd, ::content #adverts, ::content #logoAd, ::content .ad-text, ::content .ad_halfpage, ::content .adframe, ::content .adrow2, ::content .bottomAds, ::content .postad, ::content a[href^="//srv.buysellads.com/"], ::content a[href^="http://online.ladbrokes.com/promoRedirect?"], ::content a[href^="https://bs.serving-sys.com"], ::content #ad_square, ::content #adstop, ::content #bannerad, ::content .adLink, ::content .advertising_block, ::content .content_tagsAdTech, ::content a[href^="http://ad.doubleclick.net/"], ::content #head-ad, ::content #adcontainer1, ::content #player_ads, ::content .ad-label, ::content .adWrap, ::content .adsanity-group, ::content .bean-advertisment, ::content .bottomads, ::content .sky_ad, ::content #adLayer, ::content #adtext, ::content #adwrapper, ::content #homead, ::content #topAd, ::content .ad_body, ::content .ad_space, ::content .reklama, ::content .taboola-ad, ::content .widget-gpt2-ami-ads, ::content div[id^="dmRosAdWrapper"], ::content #ad-bottom, ::content #body_ad, ::content #btmsponsoredcontent, ::content #header-ads, ::content .div_adv300, ::content .searchad, ::content .sidebar-ad-slot, ::content #zergnet-widget, ::content #PreRollAd, ::content .ad468, ::content .adPod, ::content .ad_300, ::content .blog-ads, ::content .featured-ads, ::content .pubDesk, ::content .rightads, ::content .tc_ad_unit, ::content .zergnet, ::content #bottom-ads-container, ::content #contentAd, ::content #headerAd, ::content #iqadtile1, ::content #leaderboardad, ::content #sponsored_links, ::content .adResult, ::content .ads-col, ::content .plainAd, ::content .sr-in-feed-ads, ::content .td-adspot-title, ::content #ad_area, ::content .admiddle, ::content .first-ad, ::content .lbc-ad, ::content .review-ad, ::content .sidebar_ad_3, ::content #text-ads, ::content .ad_trick_header, ::content .pm-ad-zone, ::content #amzn-native-ad-0 { display: none !important; }'.
    at addElemHideSelectors (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:533:19)
    at checkLoaded (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:559:7)
    at chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/include.preload.js:575:7
    at CSSPropertyFilters.<anonymous> (chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/cssProperties.js:132:7)
csv:13 GET http://localhost:3000/primeng/resources/primeng.min.css 
**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

* **Angular version:** 2.0.X
2.4.10

* **PrimeNG version:** 2.0.X
2.0.5

**Comment by sudheerj** [comment]
The description is not clear. You need to provide step by step details on how to replicate the issue. Also please try with latest PrimeNG version. If you are still able to replicate the issue on latest versions then please create an issue with all the required details.
