### ISSUE TITLE
[Bug] PanelMenu: puipanelmenu is not a function

### ISSUE THREAD

**Issue by Luchillo** [primefaces/primeng#300]
I'm using Primeng in some parts of the dashboard and this error shows with the following code:
```html
<p-panelMenu style="width:300px">
    <div>
      <div><a data-icon="fa-file-o"><span>File</span></a></div>
      <div>
        <ul>
          <li><a data-icon="fa-plus"><span>New</span></a>
            <ul>
              <li><a><span>Project</span></a></li>
              <li><a><span>Other</span></a></li>
            </ul>
          </li>
          <li><a><span>Open</span></a></li>
          <li><a><span>Quit</span></a></li>
        </ul>
      </div>
    </div>
  </p-panelMenu>
```
Error:
```js
_originalException: TypeError: this.menuElement.puipanelmenu is not a function at PanelMenu.ngAfterViewInit (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1478:2), <anonymous>:19:26) at AppView._View_WidgetManagerComponent0.detectChangesInternal (WidgetManagerComponent.template.js:354:91) at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22) at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34) at AppView._View_DashBoardPage0.detectChangesInternal (DashBoardPage.template.js:349:8) at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22) at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34) at AppView.detectChangesInternal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:287:14) at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22) at ViewRef_.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1179:2), <anonymous>:131:65)
_originalStack: "TypeError: this.menuElement.puipanelmenu is not a function↵    at PanelMenu.ngAfterViewInit (eval at <anonymous> (http://localhost:50002/js/app.bundle.js:1478:2), <anonymous>:19:26)↵    at AppView._View_WidgetManagerComponent0.detectChangesInternal (WidgetManagerComponent.template.js:354:91)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22)↵    at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34)↵    at AppView._View_DashBoardPage0.detectChangesInternal (DashBoardPage.template.js:349:8)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22)↵    at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34)↵    at AppView.detectChangesInternal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:287:14)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22)↵    at ViewRef_.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1179:2), <anonymous>:131:65)"
_wrapperMessage: "Error in ./WidgetManagerComponent class WidgetManagerComponent - inline template:12:2"
_wrapperStack: "Error: Error in ./WidgetManagerComponent class WidgetManagerComponent - inline template:12:2↵    at ViewWrappedException.WrappedException [as constructor] (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:31:2), <anonymous>:34:31)↵    at new ViewWrappedException (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:698:2), <anonymous>:59:16)↵    at AppView._rethrowWithContext (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:329:23)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:270:22)↵    at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34)↵    at AppView._View_DashBoardPage0.detectChangesInternal (DashBoardPage.template.js:349:8)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22)↵    at AppView.detectViewChildrenChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:296:34)↵    at AppView.detectChangesInternal (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:287:14)↵    at AppView.detectChanges (eval at <anonymous> (http://localhost:50002/js/vendor.bundle.js:1173:2), <anonymous>:267:22)"
```
This image illustrates the error with the malformed menu under the date pickers.
![screen shot 2016-05-02 at 4 46 55 pm](https://cloud.githubusercontent.com/assets/9698639/14969026/a49a01d8-1085-11e6-9a00-bcecd8490033.png)

**Comment by cagataycivici** [comment]
You also need primeui-ng-all.min.js from primeui as panelmenu is one of the remaining components that have a dependency to a primeui js widget.

**Comment by Luchillo** [comment]
I did include it, however the dialog works but the panel menu don't.

**Comment by cagataycivici** [comment]
Dialog is a native component, panelMenu still depends on primeui js for the time being.

**Comment by Luchillo** [comment]
I get that it is a native component, as i said i already imported `primeui-ng-all.min.js` and the error above shows.

**Comment by cagataycivici** [comment]
Have you imported jquery as well? primeui-ng-all.min.js has jquery in it so if you have two jquerys, it will fail.

**Comment by Luchillo** [comment]
Ooohhh (0o0) i didn't know that, however the issue with that is that the project is a Ng1 project upgraded with NgUpgrade to support Ng2 code, the Ng1 itself uses JQuery and it's outside of webpack, should i just run my `vendor.js` file (which imports the `primeui-ng-all.min.js`) above that code and remove the reference to JQuery?

**Comment by Luchillo** [comment]
Ok it's done and works, i just used the copy plugin to copy `primeui-ng-all.min.js` to my `dist/js` folder and replaced the jquery code like:
```html
<script src="./js/primeui-ng-all.min.js"></script>
<!-- <script src="./jquery/jquery-2.2.3.min.js"></script> -->
```
It actually fixed another issue i had with resizable columns.

**Comment by cagataycivici** [comment]
PanelMenu is a native component so as of beta6 you won't need this script anymore to use PanelMenu.
