### ISSUE TITLE
SyntaxError: Unexpected token <, while importing primeNg components

### ISSUE THREAD

**Issue by chetanbadgujar9** [primefaces/primeng#3029]
SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:2843:16)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:3643:21
    at dynamicExecute (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:1166:26)
    at doEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:1113:13)
    at ensureEvaluate (http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:1022:13)
    at http://localhost:5555/node_modules/systemjs/dist/system.src.js?1496915947334:1042:20
    at Object.eval (http://localhost:5555/app/about/about.module.js:13:17)
    at eval (http://localhost:5555/app/about/about.module.js:30:4)
    at eval (http://localhost:5555/app/about/about.module.js:31:3) Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues

**Comment by cagataycivici** [comment]
Provide a plunkr that replicates please, it is impossible for us to find this with given info.
