### ISSUE TITLE
Angular 4 with PrimeNG throwing TypeError: this.engine.setProperty is not a function at AnimationRenderer.setProperty 

### ISSUE THREAD

**Issue by p4pramod** [primefaces/primeng#3484]
Why I am getting following error .. 
---------------------------------------------------------------------------------------------------------------
ERROR TypeError: this.engine.setProperty is not a function
    at AnimationRenderer.setProperty (eval at <anonymous> (http://localhost:8080/js/app.js:323:1), <anonymous>:521:25)
    at DebugRenderer2.setProperty (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13933:23)
    at setElementProperty (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:9587:19)
    at checkAndUpdateElementValue (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:9506:13)
    at checkAndUpdateElementInline (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:9440:24)
    at checkAndUpdateNodeInline (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12527:23)
    at checkAndUpdateNode (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12473:16)
    at debugCheckAndUpdateNode (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13334:59)
    at debugCheckRenderNodeFn (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13313:13)
    at Object.eval [as updateRenderer] (ng:///CalendarModule/Calendar.ngfactory.js:585:5)
    at Object.debugUpdateRenderer [as updateRenderer] (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13298:21)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12445:14)
    at callViewAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12805:21)
    at execComponentViewsAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12737:13)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12446:5)
    at callViewAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12805:21)
    at execComponentViewsAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12737:13)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12446:5)
    at callViewAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12805:21)
    at execEmbeddedViewsAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12763:17)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12441:5)
    at callViewAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12805:21)
    at execComponentViewsAction (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12737:13)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:12446:5)
    at callWithDebugContext (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13660:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:13200:12)
    at ViewRef_.detectChanges (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:10371:18)
    at eval (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:5009:63)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:5009:25)
    at eval (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4887:106)
    at ZoneDelegate.invoke (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:391:26)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4094:33)
    at ZoneDelegate.invoke (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:390:32)
    at Zone.run (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:141:43)
    at NgZone.run (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4025:69)
    at Object.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4887:82)
    at SafeSubscriber.schedulerFn [as _next] (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:3839:52)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:8080/js/vendor.js:27:1), <anonymous>:238:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:27:1), <anonymous>:185:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:8080/js/vendor.js:27:1), <anonymous>:125:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:27:1), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at <anonymous> (http://localhost:8080/js/vendor.js:54:1), <anonymous>:55:25)
    at EventEmitter.emit (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:3825:76)
    at checkStable (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4059:35)
    at Object.onHasTask (eval at <anonymous> (http://localhost:8080/js/vendor.js:13:1), <anonymous>:4107:21)
    at ZoneDelegate.hasTask (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:444:37)
    at ZoneDelegate._updateTaskCount (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:464:22)
    at Zone._updateTaskCount (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:288:34)
    at Zone.runTask (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:208:30)
    at drainMicroTaskQueue (eval at 572 (http://localhost:8080/js/polyfills.js:1412:1), <anonymous>:595:35)
------------------------------------------------------------------------------------------------------------------
Package Dependencies
"@angular/animations": "^4.3.1",
    "@angular/common": "~4.2.6",
    "@angular/compiler": "~4.2.6",
    "@angular/core": "~4.2.6",
    "@angular/forms": "~4.2.6",
    "@angular/http": "~4.2.6",
    "@angular/platform-browser": "~4.2.6",
    "@angular/platform-browser-dynamic": "~4.2.6",
    "@angular/router": "~4.2.6",
    "bootstrap": "^4.0.0-alpha.6",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "primeng": "^4.1.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.1",
    "tslib": "^1.7.1",
    "zone.js": "^0.8.10"

**Comment by Mrtcndkn** [comment]
Make sure that you added, "@angular/animations": "^4.3.0" to your package.json dev dependencies. If it doesn't solve your problem. What are the steps for reproducing this problem? @p4pramod

**Comment by PiSurQuatre** [comment]
I have the exact same error. Did you find a solution ? 

Adding "": "^4.3.0" to the package.json dev dependencies didnt work.

**Comment by Bhavanibhatta** [comment]
update dependencies, 
run:   npm outdated
and then, 
run:  npm update

**Comment by cagataycivici** [comment]
Glad to hear issue is resolved.
