### ISSUE TITLE
AccordionModule not working properly giving this error. Please help out! Thanks 

### ISSUE THREAD

**Issue by mahesh5b5** [primefaces/primeng#3672]
[ x ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
Uncaught Error: Template parse errors:
'p-accordionTab' is not a known element:
1. If 'p-accordionTab' is an Angular component, then verify that it is part of this module.
2. If 'p-accordionTab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

<p-accordion>
    [ERROR ->]<p-accordionTab header="Godfather I">
        The story begins as Don Vito Corleone, the head of a Ne"): ng:///HomeModule/DashboardComponent.html@30:4
'p-accordionTab' is not a known element:
1. If 'p-accordionTab' is an Angular component, then verify that it is part of this module.
2. If 'p-accordionTab' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("ns as Don Vito Corleone, the head of a New York Mafia family, overseeshis
    </p-accordionTab>
    [ERROR ->]<p-accordionTab header="Godfather III">
        After a break of more than 15 years, directo
    </p-"): ng:///HomeModule/DashboardComponent.html@33:4
'p-accordion' is not a known element:
1. If 'p-accordion' is an Angular component, then verify that it is part of this module.
2. If 'p-accordion' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("


[ERROR ->]<p-accordion>
    <p-accordionTab header="Godfather I">
        The story begins as Don Vito Corleone"): ng:///HomeModule/DashboardComponent.html@29:0
    at syntaxError (http://localhost:4200/vendor.bundle.js:47150:34)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (http://localhost:4200/vendor.bundle.js:58274:19)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:72426:39)
    at http://localhost:4200/vendor.bundle.js:72346:62
    at Set.forEach (native)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:72346:19)
    at http://localhost:4200/vendor.bundle.js:72233:19
    at Object.then (http://localhost:4200/vendor.bundle.js:47139:148)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:72232:26)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:72161:37)

**Comment by cagataycivici** [comment]
Use forum for support requests, thank you.
