### ISSUE TITLE
Universal support for pButton

### ISSUE THREAD

**Issue by Halynsky** [primefaces/primeng#4227]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ x] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```
**Current behavior**
Bug with pButton at server side rendering (Angular Universal)

```
  <p-menubar [model]="items">
    <button pButton type="button" icon="fa-cog"></button>
    <button pButton label="Logout" icon="fa-sign-out"></button>
  </p-menubar>
```

```
Node Express server listening on http://localhost:4000
ERROR ReferenceError: document is not defined
    at Button.ngAfterViewInit (E:\WorkSpase\cpa-demo\frontend\dist\server.js:129222:40)
    at callProviderLifecycles (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11450:18)
    at callElementProvidersLifecycles (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11421:13)
    at callLifecycleHooksChildrenFirst (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11405:17)
    at checkAndUpdateView (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12533:5)
    at callViewAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12873:21)
    at execComponentViewsAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12805:13)
    at checkAndUpdateView (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12531:5)
    at callViewAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12873:21)
    at execComponentViewsAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12805:13)
[Error]
TypeError: this.el.nativeElement.hasChildNodes is not a function
    at Button.ngOnDestroy (E:\WorkSpase\cpa-demo\frontend\dist\server.js:129280:38)
    at callProviderLifecycles (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11456:18)
    at callElementProvidersLifecycles (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11421:13)
    at callLifecycleHooksChildrenFirst (E:\WorkSpase\cpa-demo\frontend\dist\server.js:11405:17)
    at destroyView (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12744:5)
    at callViewAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12893:13)
    at execComponentViewsAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12805:13)
    at destroyView (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12743:5)
    at callViewAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12893:13)
    at execComponentViewsAction (E:\WorkSpase\cpa-demo\frontend\dist\server.js:12805:13)
```

**What is the motivation / use case for changing the behavior?**
Server side rendering to speed up an app

* **Angular version:** 4.4.6

* **PrimeNG version:** 4.2.2

* **Node (for AoT issues):** `node --version` =   v8.6.0

**Comment by cagataycivici** [comment]
Please p-button element for universal support.

**Comment by Pardeep9stacks** [comment]
Still facing the same issue `document is not defined` with angular universal. I am using
Primeng - 6.1.4
Angular - 6.1.0

**Comment by gkaran** [comment]
Doesn't seem that the problem is resolved. Any reason why it was closed without an explanation at least?

**Comment by charlatan154** [comment]
This issue still exists..

**Comment by brunnoDatum** [comment]
I am having this too

**Comment by acuetoblumer** [comment]
Having this too...

**Comment by atiberghien** [comment]
Still exists (and in GalleriaThumbnails component too)

**Comment by D-LUSiON** [comment]
Brothers and sisters, this issue is from 2017 and still exists! And the solution is one (yes, ONE) minute of work!

Import this:

`import { DOCUMENT } from '@angular/common';`

Then here:

[src/app/components/button/button.ts#L29](https://github.com/primefaces/primeng/blob/master/src/app/components/button/button.ts#L29)

(in the constructor)

just add:

`@Inject(DOCUMENT) private document: Document`

and then replace all references to `document` with `this.document`. This should be done in all other files where are used browser specific stuff so it can be used in SSR.

I just don't have time to make pull requests...

**Comment by tachtouktayoub** [comment]
Having this too...
