### ISSUE TITLE
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by Deilan** [primefaces/primeng#4379]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
Error:
```
Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\primeng\node_modules\html-webpack-plugin\lib\compiler.js:11:26)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\primeng\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Expected behavior**
`npm install && npm start` works fine

**Minimal reproduction of the problem with instructions**
1. `git clone https://github.com/primefaces/primeng.git`
2. `npm install`
3. `npm start`

**Please tell us about your environment:**
Windows 10 x64
Node 8.9.0
npm 5.5.1
Angular CLI 1.5.0

**Comment by Crazybutch** [comment]
Delete node_modules Folder and package-lock.json File -> rerun npm install

**Comment by ManojSethuraman** [comment]
This can be resolved by installing webpack using `npm instal webpack`. I used this method to resolve the error for me.

**Comment by cagataycivici** [comment]
Not a PrimeNG issue.
