### ISSUE TITLE
[Error] [Calandar] datetimepicker

### ISSUE THREAD

**Issue by djavrell** [primefaces/primeng#439]
I have an error with the calandar component, the error is caused by [the line 181](https://github.com/primefaces/primeng/blob/master/components/calendar/calendar.ts) in this file

Have you an idea to solve this issue ?

**I use:**
- webpack@1.13.1
- primeng@1.0.0-beta.6
- primeui@4.1.12
- jquery@2.2.4
- ng2-bootstrap@1.0.16

here is the stack trace generate by the browser:

> TypeError: this.calendarElement.datetimepicker is not a function
    at Calendar.ngAfterViewInit (http://localhost:3000/main.bundle.js:33213:35)
    at DebugAppView._View_DateComponent1.detectChangesInternal (DateComponent.template.js:758:89)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:42731:38)
    at DebugAppView._View_DateComponent0.detectChangesInternal (DateComponent.template.js:396:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:42736:35)
    at DebugAppView._View_PathComponent0.detectChangesInternal (PathComponent.template.js:446:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:42736:35)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/vendor.bundle.js:42727:15)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:42731:38)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/vendor.bundle.js:42726:15)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:42731:38)
    at DebugAppView._View_AddPathComponent0.detectChangesInternal (AddPathComponent.template.js:80:8)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:42736:35)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/vendor.bundle.js:42727:15)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:3000/vendor.bundle.js:42731:38)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/vendor.bundle.js:42726:15)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:3000/vendor.bundle.js:42736:35)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:3000/vendor.bundle.js:42727:15)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.bundle.js:42716:15)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.bundle.js:42805:45)
    at ViewRef_.detectChanges (http://localhost:3000/vendor.bundle.js:31463:66)
    at http://localhost:3000/vendor.bundle.js:18961:85
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:3000/vendor.bundle.js:18961:39)
    at http://localhost:3000/vendor.bundle.js:18867:126
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15186:30)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://localhost:3000/vendor.bundle.js:33333:42)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15185:36)
    at Zone.run (http://localhost:3000/polyfills.bundle.js:15079:45)
    at NgZoneImpl.runInner (http://localhost:3000/vendor.bundle.js:33364:72)
    at NgZone.run (http://localhost:3000/vendor.bundle.js:21452:67)
    at Object.next (http://localhost:3000/vendor.bundle.js:18867:102)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/vendor.bundle.js:8347:53)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/vendor.bundle.js:10154:17)
    at SafeSubscriber.next (http://localhost:3000/vendor.bundle.js:10103:23)
    at Subscriber._next (http://localhost:3000/vendor.bundle.js:10053:27)
    at Subscriber.next (http://localhost:3000/vendor.bundle.js:10017:19)
    at EventEmitter.Subject._finalNext (http://localhost:3000/vendor.bundle.js:8096:31)
    at EventEmitter.Subject._next (http://localhost:3000/vendor.bundle.js:8088:19)
    at EventEmitter.Subject.next (http://localhost:3000/vendor.bundle.js:8045:15)
    at EventEmitter.emit (http://localhost:3000/vendor.bundle.js:8336:77)
    at NgZone._checkStable (http://localhost:3000/vendor.bundle.js:21370:45)
    at NgZoneImpl.NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.setMicrotask (http://localhost:3000/vendor.bundle.js:21346:24)
    at Object.NgZoneImpl.inner.inner.fork.onHasTask (http://localhost:3000/vendor.bundle.js:33345:36)
    at ZoneDelegate.hasTask (http://localhost:3000/polyfills.bundle.js:15245:57)
    at ZoneDelegate._updateTaskCount (http://localhost:3000/polyfills.bundle.js:15262:28)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15223:28)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15119:49)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.bundle.js:15337:37)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15289:23)
BrowserDomAdapter.logError	@	browser_adapter.js:77
ExceptionHandler.call	@	exception_handler.js:70
(anonymous function)	@	application_ref.js:265
schedulerFn	@	async.js:123
SafeSubscriber.__tryOrUnsub	@	Subscriber.js:225
SafeSubscriber.next	@	Subscriber.js:174
Subscriber._next	@	Subscriber.js:124
Subscriber.next	@	Subscriber.js:88
Subject._finalNext	@	Subject.js:128
Subject._next	@	Subject.js:120
Subject.next	@	Subject.js:77
EventEmitter.emit	@	async.js:112
NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError	@	ng_zone.js:120
NgZoneImpl.inner.inner.fork.onHandleError	@	ng_zone_impl.js:66
ZoneDelegate.handleError	@	zone.js:327
Zone.runTask	@	zone.js:259
drainMicroTaskQueue	@	zone.js:474
ZoneTask.invoke	@	zone.js:426

**Comment by cagataycivici** [comment]
You need to add jquery ui datepicker plugin, simple way it adding node_modules/primeui/primeui-ng-all.min.js

**Comment by rogueRabbit** [comment]
I have the same problem, how do you solve it in the end, is the introduction of UI datepicker plugin jquery @djavrell
