### ISSUE TITLE
jQuery(...).puicolreorder is not a function

### ISSUE THREAD

**Issue by MarcelCremer** [primefaces/primeng#440]
Hello,

the new Data table throws an Exception when someone is changing the route.

Example: http://www.primefaces.org/primeng/#/datatablecolreorder
How: Click for example on "Setup" at the top right
Exception:
zone.js:461 Unhandled Promise rejection: EXCEPTION: Error in showcase/demo/datatable/datatablecolreorderdemo.html:10:4
ORIGINAL EXCEPTION: TypeError: jQuery(...).puicolreorder is not a function
ORIGINAL STACKTRACE:
TypeError: jQuery(...).puicolreorder is not a function
    at DataTable.ngOnDestroy (http://www.primefaces.org/primeng/components/datatable/datatable.js:822:55)
    at DebugAppView._View_DataTableColReorderDemo0.destroyInternal (DataTableColReorderDemo.template.js:435:24)
    at DebugAppView.AppView.destroyLocal (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/view.js:144:14)
    at DebugAppView.destroyLocal (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/view.js:279:43)
    at DebugAppView.AppView._destroyRecurse (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/view.js:133:14)
    at DebugAppView.AppView._destroyRecurse (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/view.js:131:25)
    at DebugAppView.AppView.destroy (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/view.js:119:14)
    at ComponentRef_.destroy (http://www.primefaces.org/primeng/node_modules/@angular/core/src/linker/component_factory.js:113:82)
    at RouterOutlet.unload (http://www.primefaces.org/primeng/node_modules/@angular/router/src/directives/router_outlet.js:12:22)
    at _LoadSegments.unloadOutlet (http://www.primefaces.org/primeng/node_modules/@angular/router/src/router.js:267:24)
ERROR CONTEXT:

Best Regards
Marcel

**Comment by mertsincan** [comment]
Please try 1.0.0-beta.8;
https://github.com/primefaces/primeng/issues/432
