### ISSUE TITLE
New InputMask Component

### ISSUE THREAD

**Issue by cagataycivici** [primefaces/primeng#510]
Create an input mask components based on jquery.inputmask https://github.com/RobinHerbots/jquery.inputmask

**Comment by vishaltechreceptives** [comment]
When i use InputMask it will through a error like,

```
ORIGINAL EXCEPTION: TypeError: jQuery(...).inputmask is not a function
TypeError: jQuery(...).inputmask is not a function
    at InputMask.ngAfterViewInit (inputmask.js:63)
    at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:2208)
    at DebugAppView.AppView.detectChanges (core.umd.js:12143)
    at DebugAppView.detectChanges (core.umd.js:12247)
    at DebugAppView.AppView.detectViewChildrenChanges (core.umd.js:12169)
    at DebugAppView.AppView.detectChangesInternal (core.umd.js:12154)
    at DebugAppView.AppView.detectChanges (core.umd.js:12143)
    at DebugAppView.detectChanges (core.umd.js:12247)
    at ViewRef_.detectChanges (core.umd.js:10397)
    at eval (core.umd.js:9911)
```

**Comment by patty-victor** [comment]
I'm stuck at the same error @vishaltechreceptives and cannot find a way out of it.

`ORIGINAL EXCEPTION: TypeError: jQuery(...).inputmask is not a function
ORIGINAL STACKTRACE:
TypeError: jQuery(...).inputmask is not a function
    at InputMask.ngAfterViewInit (http://localhost:8080/H94SP02/site/node_modules/primeng/components/inputmask/inputmask.js:57:67)
    at DebugAppView._View_TIInputText0.detectChangesInternal (TIInputText.template.js:59:89)
    at DebugAppView.AppView.detectChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:234:14)
    at DebugAppView.detectChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:339:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:260:19)
    at DebugAppView._View_TesteComponentes0.detectChangesInternal (TesteComponentes.template.js:122:8)
    at DebugAppView.AppView.detectChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:234:14)
    at DebugAppView.detectChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:339:44)
    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:260:19)
    at DebugAppView.AppView.detectChangesInternal (http://localhost:8080/H94SP02/site/node_modules/@angular/core/src/linker/view.js:245:14)`

**Comment by tbertran** [comment]
Having the same problem.
It's coming from this line in `inputmask.ts`:
`jQuery(this.el.nativeElement.children[0])['inputmask'](cfg);`

Anybody know what that associative array (weird, to begin with) is trying to do?

**Comment by patty-victor** [comment]
@tbertran I solved this problem by downloading the following plugin and adding it to my mode_modules folder. 

[https://github.com/RobinHerbots/jquery.inputmask](url)

Then, I just had to set this path on my `index.html` inserting these to lines: 
`<script src="node_modules/primeui/primeui-ng-all.min.js"></script> 
<script src="node_modules/jquery.inputmask-3.x/dist/jquery.inputmask.bundle.js"></script>`

Good to remember that `primeui-ng-all.min.js` must be referenced BEFORE `jquery.inputmask.bundle.js` because it contains all jQuery definitions that inputmask needs.

**Comment by dan-madaket** [comment]
The documentation says this supports "email" input masking... but there is not example and I can't figure it out.

How do you write a mask with variable characters?
