### ISSUE TITLE
Existence check missing in Calendar component's ngOnDestroy method

### ISSUE THREAD

**Issue by p370** [primefaces/primeng#538]
The calendar is created inside ngAfterViewInit method of Calendar component, but it can happen that the ngAfterViewInit is never executed but ngOnDestroy is. For example, it happens when navigation happens inside ngOnInit of a component which uses the Calendar component inside its template.

The result is following:

```
TypeError: Cannot read property 'datepicker' of undefined
    at Calendar.ngOnDestroy (http://localhost:8080/lib/primeng/components/calendar/calendar.js:123:29)
    at DebugAppView._View_RecipientsListComponent0.destroyInternal (RecipientsListComponent.template.js:545:23)
    at DebugAppView.AppView.destroyLocal (http://localhost:8080/lib/@angular/core/src/linker/view.js:144:14)
    at DebugAppView.destroyLocal (http://localhost:8080/lib/@angular/core/src/linker/view.js:279:43)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8080/lib/@angular/core/src/linker/view.js:133:14)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8080/lib/@angular/core/src/linker/view.js:131:25)
    at DebugAppView.AppView.destroy (http://localhost:8080/lib/@angular/core/src/linker/view.js:119:14)
    at ComponentRef_.destroy (http://localhost:8080/lib/@angular/core/src/linker/component_factory.js:113:82)
    at RouterOutlet.unload (http://localhost:8080/lib/@angular/router/src/directives/router_outlet.js:12:22)
    at _LoadSegments.unloadOutlet (http://localhost:8080/lib/@angular/router/src/router.js:267:24)

... (rest omitted)
```

**Comment by shortthirdman** [comment]
I am having the same problem : Cannot read property 'datepicker' of undefined. Using PrimeNG version 1.0.0-beta.16

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
