### ISSUE TITLE
[(ngModel)] for Autocomplete and Multi-Select is not working after upgrading to beta.9.

### ISSUE THREAD

**Issue by swarke** [primefaces/primeng#557]
Reference - http://forum.primefaces.org/viewtopic.php?f=35&t=46205&sid=1274ab536c35961643b7ee0ee74515b0

ORIGINAL EXCEPTION: No value accessor for ''
ORIGINAL STACKTRACE:
Error: No value accessor for ''
    at new BaseException (http://localhost:5555/node_modules/@angular/forms/src/facade/exceptions.js:20:23)
    at _throwError (http://localhost:5555/node_modules/@angular/forms/src/directives/shared.js:47:11)
    at Object.setUpControl (http://localhost:5555/node_modules/@angular/forms/src/directives/shared.js:22:9)
    at NgModel._addStandaloneControl (http://localhost:5555/node_modules/@angular/forms/src/directives/ng_model.js:84:18)
    at NgModel._addControl (http://localhost:5555/node_modules/@angular/forms/src/directives/ng_model.js:80:18)
    at NgModel.ngOnChanges (http://localhost:5555/node_modules/@angular/forms/src/directives/ng_model.js:38:18)

**Comment by sdmoralesma** [comment]
Please refer to my answer here: https://github.com/primefaces/primeng/issues/549

**Comment by ducduongtmb** [comment]
@sdmoralesma Sorry . I don't understand your solution . I have same problem , I use angular Rc4 . when I use [(model)] instead [(ngModel)] . I can't get data from Autocomplete Multiple

**Comment by sdmoralesma** [comment]
You can check other solutions that are explained, I know that some people had good results with different approaches. That depends on you configuration.

**Comment by Mrtcndkn** [comment]
Please try with the latest PrimeNG version and comment if the issue still persists.
