### ISSUE TITLE
DomHandler utility incompatible to use with Angular Universal

### ISSUE THREAD

**Issue by debapamdas** [primefaces/primeng#5851]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using turbo table for server side rendering(angular universal) it throws error in server.

ERROR ReferenceError: getComputedStyle is not defined
    at e.scrollInView (D:\Project\Angular\my-ssr-project\dist-server\main.bundle.js:1:38193)
    at e.ngAfterViewChecked (D:\Project\Angular\my-ssr-project\dist-server\main.bundle.js:1:59483)
    at callProviderLifecycles (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:12789:18)
    at callElementProvidersLifecycles (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:12753:13)
    at callLifecycleHooksChildrenFirst (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:12736:29)
    at checkAndUpdateView (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:13891:5)
    at callViewAction (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:14233:21)
    at execEmbeddedViewsAction (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:14191:17)
    at checkAndUpdateView (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:13883:5)
    at callViewAction (D:\Project\Angular\my-ssr-project\node_modules\@angular\core\bundles\core.umd.js:14233:21)

**Expected behavior**
There should be no error in server while using angular universal

**What is the motivation / use case for changing the behavior?**
use primeng along with angular universal for server side rendering

**Please tell us about your environment:**
os: win 7
node: 10.2.1

* **Angular version:** 5.X
 angular 5.2.11

* **PrimeNG version:** 5.X
primeng: 6.0.0-alpha.2

**Comment by yigitfindikli** [comment]
I’m unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
https://stackblitz.com/github/primefaces/primeng-issue-template
