### ISSUE TITLE
The local test suite never finishes and stales at 40 test

### ISSUE THREAD

**Issue by peterblazejewicz** [primefaces/primeng#5928]
**I'm submitting a ...**
```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Plunkr Case (Bug Reports)**
n/a

**Current behavior**

The `RadioButton should display active state initially when checked by default` fails with:
```
etworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/RadioButton.ngfactory.js'.
Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'ng:///DynamicTestModule/RadioButton.ngfactory.js'.
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:2990:1
    at XMLHttpRequest.proto.(anonymous function) [as send] (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:1394:1)
    at Array.<anonymous> (http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:111:263)
    at http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:105:5
    at Array.<anonymous> (http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:112:128)
    at http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:105:5
    at d (http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:105:316)
    at r (http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:108:356)
    at http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/source-map-support/browser-source-map-support.js:109:245
    at Array.map (<anonymous>)
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4470:23
```
This looks like:
https://github.com/angular/angular-cli/issues/7296

When I switch to Safari runner the test immediately fails:

```
RadioButton should display active state initially when checked by default
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ui-state-active: false'. Current value: 'ui-state-active: true'. in http://localhost:9876/_karma_webpack_/vendor.js (line 44587)
viewDebugError@http://localhost:9876/_karma_webpack_/vendor.js:44587:24
checkBindingNoChanges@http://localhost:9876/_karma_webpack_/vendor.js:44677:58
checkNoChangesNodeInline@http://localhost:9876/_karma_webpack_/vendor.js:47545:30
checkNoChangesNode@http://localhost:9876/_karma_webpack_/vendor.js:47532:33
debugCheckNoChangesNode@http://localhost:9876/_karma_webpack_/vendor.js:48139:29
debugCheckDirectivesFn@http://localhost:9876/_karma_webpack_/vendor.js:48067:36

checkNoChangesView@http://localhost:9876/_karma_webpack_/vendor.js:47431:30
callViewAction@http://localhost:9876/_karma_webpack_/vendor.js:47670:39
execComponentViewsAction@http://localhost:9876/_karma_webpack_/vendor.js:47632:27
checkNoChangesView@http://localhost:9876/_karma_webpack_/vendor.js:47434:29
callWithDebugContext@http://localhost:9876/_karma_webpack_/vendor.js:48346:30
checkNoChanges@http://localhost:9876/_karma_webpack_/vendor.js:45842:82
checkNoChanges@http://localhost:9876/_karma_webpack_/vendor.js:54099:56
_tick@http://localhost:9876/_karma_webpack_/vendor.js:54065:32
http://localhost:9876/_karma_webpack_/vendor.js:54083:54
onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:40204:39
run@http://localhost:9876/_karma_webpack_/polyfills.js:7034:49
detectChanges@http://localhost:9876/_karma_webpack_/vendor.js:54083:28
http://localhost:9876/_karma_webpack_/main.js:20259:30
run@http://localhost:9876/_karma_webpack_/polyfills.js:7034:49
attempt@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4478:50
run@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4402:27
execute@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4384:13
execute@http://localhost:9876/_karma_webpack_/vendor.js:91144:46
queueRunnerFactory@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:964:42
execute@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:563:28
fn@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:5541:44
attempt@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4486:30
run@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4402:27
execute@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4384:13
execute@http://localhost:9876/_karma_webpack_/vendor.js:91144:46
queueRunnerFactory@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:964:42
fn@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:5526:31
attempt@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4486:30
run@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4402:27
runNext@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4446:23
http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4453:20
http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:4356:17
onComplete@http://localhost:9876/absolute/Users/piotrblazejewicz/git/primeng/node_modules/jasmine-core/lib/jasmine-core/jasmine.js?0b1eaf7a13cae32191eadea482cfc96ae41fc22b:5529:21
runTask@http://localhost:9876/_karma_webpack_/polyfills.js:7084:57
drainMicroTaskQueue@http://localhost:9876/_karma_webpack_/polyfills.js:7491:42
promiseReactionJob@[native code]
```

**Expected behavior**
n/a

**Minimal reproduction of the problem with instructions**

```
npm install
npm test

```
**What is the motivation / use case for changing the behavior?**
I cannot verify the integrity of libary if I made a change

**Please tell us about your environment:**
Chrome 69.0.3451 (Mac OS X 10.13.5) 
NPM 5.6.*
Node 9.3.*
PrimeNG: 6.0.0-SNAPSHOT

* **Angular version:** 5.X
n/a

* **PrimeNG version:** 5.X
6.0.0-SNAPSHOT

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome via Karma runner
Chrome 69.0.3451 (Mac OS X 10.13.5) 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
n/a

* **Node (for AoT issues):** `node --version` =   
n/a

**Comment by cagataycivici** [comment]
I'm unable to replicate with the latest PrimeNG. If the issue still persists with the new version please create a new issue with our stackblitz template.
