### ISSUE TITLE
Drag and Drop not working in IE11

### ISSUE THREAD

**Issue by gatapia** [primefaces/primeng#632]
On demo page: http://www.primefaces.org/primeng/#/dragdrop

Just try to drag into the table.  Error is:

```
SCRIPT5022: EXCEPTION: Error in showcase/demo/dragdrop/dragdropdemo.html:23:20
ORIGINAL EXCEPTION: Error: Unexpected call to method or property access.
ORIGINAL STACKTRACE:
Error: Unexpected call to method or property access.
   at Draggable.prototype.dragStart (eval code:26:13)
   at _View_anonymous_token_68_1.prototype._handle_dragstart_0_2 (Function code:1772:3)
   at Anonymous function (eval code:366:17)
   at Anonymous function (eval code:246:9)
   at Anonymous function (eval code:20:104)
   at ZoneDelegate.prototype.invoke (http://www.primefaces.org/primeng/node_modules/zone.js/dist/zone.js:321:14)
   at onInvoke (eval code:46:25)
   at ZoneDelegate.prototype.invoke (http://www.primefaces.org/primeng/node_modules/zone.js/dist/zone.js:321:14)
   at Zone.prototype.runGuarded (http://www.primefaces.org/primeng/node_modules/zone.js/dist/zone.js:230:22)
   at NgZoneImpl.prototype.runInnerGuarded (eval code:79:60)
ERROR CONTEXT:
[object Object]
File: zone.js, Line: 260, Column: 26
```

**Comment by billdwhite** [comment]
Same problem here

**Comment by afelke** [comment]
It seems that the code in line 37 of file "primeng/components/dragdrop/dragdrop.ts" causes the issue with IE11:

`event.dataTransfer.setData(this.scope, this.scope);`

`this.scope` is passed twice - as the format and as the data. I think it should be something like the following (which would at least make it work in IE11):

`event.dataTransfer.setData('text', this.scope);`
