### ISSUE TITLE
Serverside rendering using @ng-toolkit/universal fails with errormessage: ReferenceError: MouseEvent is not defined

### ISSUE THREAD

**Issue by Susanne1208** [primefaces/primeng#6472]
**I'm submitting a ...**  (check one with "x")
```
[ X] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primeng/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=35
```

**Current behavior**
When using @ng-toolkit/universal for serverside rendering, building (npm run build) is possible but when I run npm run server (node local.js) it fails with error message: 
...
Using browser-only version of superagent in non-browser environment
C:\Users\user\source\repos\my-repo\my-app\dist\server.js:116111
        __metadata("design:paramtypes", [MouseEvent]),
                                         ^

ReferenceError: MouseEvent is not defined
    at C:\Users\user\source\repos\my-repo\my-app\dist\server.js:116111:42
    at Object.module.exports.c (CC:\Users\user\source\repos\my-repo\my-app\dist\server.js:116126:2)
    at __webpack_require__ (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:21:30)
    at Object.primeng/components/table/table (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:142724:18)
    at __webpack_require__ (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:121944:30)
    at Object../src/app/category/category.component.ngfactory.js (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:139657:11)
    at __webpack_require__ (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:121944:30)
    at Object../src/app/project/project.component.ngfactory.js (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:141078:10)
    at __webpack_require__ (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:121944:30)
    at Object../src/app/app.server.module.ngfactory.js (C:\Users\user\source\repos\my-repo\my-app\dist\server.js:139340:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iit-estimate-app@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iit-estimate-app@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-09-07T07_30_29_705Z-debug.log
...

I've found that TurboTable can be a part of the problem: 
#5670 https://github.com/primefaces/primeng/issues/4904

* **Angular version:** 6.1.1

* **PrimeNG version:** 6.1.0
 
* **Language:** TypeScript X.X

**Comment by marticrespi** [comment]
I have the same problem with universal, when I build it works well, but when I try to serve the universal build, it shows me an error like yours, but about KeyboarEvent, I don't use the KeyFilterModule in my project.

I was using 6.0.1 version, I have tried to update to 6.1.4 and the error still occurring.

````
ReferenceError: KeyboardEvent is not defined
    at D:\XXXXX\node_modules\primeng\components\keyfilter\keyfilter.js:132:42
    at Object.<anonymous> (D:\XXXX\node_modules\primeng\components\keyfilter\keyfilter.js:144:2)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\XXXXXX\node_modules\primeng\primeng.js:44:10)
````

**Comment by kay-schecker** [comment]
I'm also facing this issue. Is there any workaround or fix available?

**Comment by cagataycivici** [comment]
@yigitfindikli Please take over, this issue may expand to "Angular Universal Support for all components".

**Comment by kadosh1000** [comment]
@cagataycivici any news on this issue? 
I am using primeng's components all over my app, this issue keeps me from deploying to production as I must use universal (for SEO reasons)

**Comment by cagataycivici** [comment]
I think this should be handled at universal side, we need to use events such as MouseEvent, KeyboardEvent. Following link has various workarounds at universal config.

https://github.com/swimlane/ngx-charts/issues/460

**Comment by Rayleigh3105** [comment]
@kadosh1000 How did you proceed with your problem? I´m also using PrimeNG components and got the same error when doing SSR.

**Comment by sunojvijayan** [comment]
Any update in this?

**Comment by lquastana** [comment]
I found this workaround : 
just before my import i add these lines 
`global['window'] = [];
global['MouseEvent'] = [];`

In my case it work

An 2nd workaround is to exclude with webpack : 

` module: {
    rules: [
      { test: /\.(ts|js)$/, loader: 'regexp-replace-loader', options: { match: { pattern: '\\[(Mouse|Keyboard)Event\\]', flags: 'g' }, replaceWith: '[]', } },
      { test: /\.ts$/, loader: 'ts-loader' },
    ]
  },`
