### ISSUE TITLE
Maximum call stack size exceeded at DomHandler.equals

### ISSUE THREAD

**Issue by shahmuratov** [primefaces/primeng#668]
Hi everyone!
Version: 1.0.0-beta.9. I'm recieving this error after some work with prime ng autocomplete

EXCEPTION: Error in ./AutoComplete class AutoComplete - inline template:3:112

Here is call stack
RangeError: Maximum call stack size exceeded

    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:218:44)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)
    at DomHandler.equals (<host>/node_modules/primeng/components/dom/domhandler.js:232:35)

What can I do to avoid this issue?

**Comment by shahmuratov** [comment]
Turned out to be circular reference in object. Closing
