### ISSUE TITLE
Element is not defined in TextEditor

### ISSUE THREAD

**Issue by Gamblt** [primefaces/primeng#7122]
```
[x ] bug report
```

**Current behavior**
I've got error when i run angular server-side rendering.
```
__metadata("design:type", Element)
                                  ^
ReferenceError: Element is not defined
    at /project/dist/server/server.js:197009:35
    at Object.defineProperty.value (/project/dist/server/server.js:197037:2)
    at __webpack_require__ (/project/dist/server/server.js:20:30)
    at Object.primeng/components/editor/editor (/project/dist/server/server.js:158866:18)
    at __webpack_require__ (/project/dist/server/server.js:133611:30)
    at Object../src/app/app.server.module.ngfactory.js (/project/dist/server/server.js:144638:12)
    at __webpack_require__ (/project/dist/server/server.js:133611:30)
    at Object../src/main.server.ts (/project/dist/server/server.js:158628:37)
    at __webpack_require__ (/project/dist/server/server.js:133611:30)
    at Object.0 (/project/dist/server/server.js:158656:18)

```
Error in primeng/componnets/editor/editor.js file
```
 __decorate([
        core_1.Input(),
        __metadata("design:type", Element)
    ],
\
```

**Expected behavior**
Success build run.

**Please tell us about your environment:**
Ubuntu: 16.04
Angular: 7.2.1
PrimeNG: 7.0.4
TypeScript: 3.2.2
NodeJS: 8.15.0

**Comment by Gamblt** [comment]
I'll go back to primeng@7.0.0 and error has gone.

**Comment by yigitfindikli** [comment]
Hi,
I think it's not about PrimeNG. It's an angular universal problem. You can find solution in here https://github.com/angular/angular/issues/27732

If issue still persist then please let me know.

**Comment by yigitfindikli** [comment]
I cannot see any update, i suppose this issue resolved. If it's not resolved then please let me know. We can reopened issue.

**Comment by Gamblt** [comment]
> You can find solution in here [angular/angular#27732](https://github.com/angular/angular/issues/27732)

Related to this link, primeng use unstable feature and this issue will be fixed when angular merge related [fixes](https://github.com/vikerman/domino/pull/1) from domino lib.

I've create temporary fix [PR](https://github.com/primefaces/primeng/pull/7178)

**Comment by sispor** [comment]
I fixed error "Element is not defined" deleting  "ng-inline-svg": "^8.5.1", in package.json, Angular 9
