### ISSUE TITLE
DataTableModule keep throwing Hammer.js is not loaded, can not bind dragstart event.

### ISSUE THREAD

**Issue by Efactor888** [primefaces/primeng#784]
Hello,

Been struggling to figure this out for days now, any help will be greatly appreciated. Using Angular CLI rc5.

EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./DataTable class DataTable - inline template:22:190
ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind dragstart event
ORIGINAL STACKTRACE:
Error: Hammer.js is not loaded, can not bind dragstart event
    at new BaseException (http://localhost:4200/vendor/@angular/platform-browser/src/facade/exceptions.js:27:23)
    at HammerGesturesPlugin.supports (http://localhost:4200/vendor/@angular/platform-browser/src/dom/events/hammer_gestures.js:56:19)
    at EventManager._findPluginFor (http://localhost:4200/vendor/@angular/platform-browser/src/dom/events/event_manager.js:37:24)
    at EventManager.addEventListener (http://localhost:4200/vendor/@angular/platform-browser/src/dom/events/event_manager.js:24:27)
    at DomRenderer.listen (http://localhost:4200/vendor/@angular/platform-browser/src/dom/dom_renderer.js:161:48)
    at DebugDomRenderer.listen (http://localhost:4200/vendor/@angular/core/src/debug/debug_renderer.js:89:31)
    at DebugAppView._View_DataTable5.createInternal (DataTable.ngfactory.js:864:36)
    at DebugAppView.AppView.create (http://localhost:4200/vendor/@angular/core/src/linker/view.js:101:21)
    at DebugAppView.create (http://localhost:4200/vendor/@angular/core/src/linker/view.js:314:44)
    at TemplateRef_.createEmbeddedView (http://localhost:4200/vendor/@angular/core/src/linker/template_ref.js:59:14)
ERROR CONTEXT:
[object Object]

**Comment by cagataycivici** [comment]
This is really weird, we don't use hammer.js at all. Do you have it in your app?

**Comment by cagataycivici** [comment]
Closing as can't replicate.
