### ISSUE TITLE
"Not defined" error after compiling SSR in Angular 9.0.

### ISSUE THREAD

**Issue by MehmetSert** [primefaces/primeng#8548]
```
[x ] bug report
[ ] feature request
[ ] support request
```

```
ReferenceError: document is not defined
    at ConfirmDialog../node_modules/primeng/bundles/primeng-confirmdialog.umd.js.ConfirmDialog.disableModality (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:175811:44)
    at ConfirmDialog../node_modules/primeng/bundles/primeng-confirmdialog.umd.js.ConfirmDialog.onOverlayHide (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:175873:18)
    at ConfirmDialog../node_modules/primeng/bundles/primeng-confirmdialog.umd.js.ConfirmDialog.ngOnDestroy (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:175879:18)
    at executeOnDestroys (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:65591:41)
    at cleanUpView (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:65520:13)
    at destroyViewTree (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:65320:51)
    at destroyLView (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:65473:13)
    at RootViewRef../node_modules/@angular/core/bundles/core.umd.js.ViewRef.destroy (/Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:66206:13)
    at /Users/mehmetsert/Development/git/kodumunblogu/dist/kodumunblogu/server/main.js:84654:71
    at Array.forEach (<anonymous>)
```

* **Angular version:** 9.0.0
* **PrimeNG version:** 9.0.0-rc.4
* **Node (for AoT issues):** `node --version` =   10.14.2

**Comment by yigitfindikli** [comment]
Hi @MehmetSert, I couldn't replicate using with https://github.com/primefaces/primeng-quickstart-cli. Can you provide sample project?

**Comment by zorrme** [comment]
I have the same issue with angular universal

**Comment by cagataycivici** [comment]
Glad to hear issue is resolved.
