### ISSUE TITLE
Error when importing FileUploadModule

### ISSUE THREAD

**Issue by jleuleu** [primefaces/primeng#869]
I added the FileUploadModule in my "imports" section of NgModule.
Now I receive an error when starting the application.

```
zone.js:461 Unhandled Promise rejection: Error: Can't resolve all parameters for FileUpload: (?).
	    at new BaseException (http://local-dev.com/ng2/vendor/@angular/compiler/src/facade/exceptions.js:27:23)
	    at CompileMetadataResolver.getDependenciesMetadata (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:551:19)
	    at CompileMetadataResolver.getTypeMetadata (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:448:26)
	    at CompileMetadataResolver.getDirectiveMetadata (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:200:28)
	    at eval (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:267:49)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:260:44)
	    at eval (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:252:54)
	    at Array.forEach (native)
	    at CompileMetadataResolver.getNgModuleMetadata (http://local-dev.com/ng2/vendor/@angular/compiler/src/metadata_resolver.js:239:44)
	Evaluating http://local-dev.com/ng2/main.js
	Error loading http://local-dev.com/ng2/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Can't resolve all parameters for FileUpload: (?).(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: Error: Can't resolve all parameters for FileUpload: (?).(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
```

Am I missing a dependency?

Info:
primeng 1.0.0-beta.15
angular 2.0.0-rc.5

**Comment by jleuleu** [comment]
I updated to angular 2 RC6 and it works now.
