### ISSUE TITLE
Primeng10 breaks alongside Angular10

### ISSUE THREAD

**Issue by e4r** [primefaces/primeng#9277]
**I'm submitting a ...**
```
[*] bug report 
```

**Current behavior**
Upgrading from Primeng9 to Primeng10, alongside with Angular 10 breaks the compiling. Even though the stackblitz above works, when I run "npm i" on my machine the compiler returns an obscure error:

* (node:10156) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.typeToValue (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\type_to_value.js:45:66)
    at C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\typescript.js:75:58
    at Array.map (<anonymous>)
    at TypeScriptReflectionHost.getConstructorParameters (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\typescript.js:57:36)
    at Object.getConstructorDependencies (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:29:36)
    at Object.extractDirectiveMetadata (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:243:34)
    at ComponentDecoratorHandler.analyze (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:145:47)
    at TraitCompiler.analyzeTrait (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:346:40)
    at analyze (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:298:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:10156) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at Object.typeToValue (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\type_to_value.js:45:66)
    at C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\typescript.js:75:58
    at Array.map (<anonymous>)
    at TypeScriptReflectionHost.getConstructorParameters (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\reflection\src\typescript.js:57:36)
    at Object.getConstructorDependencies (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\util.js:29:36)
    at Object.extractDirectiveMetadata (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\directive.js:243:34)
    at ComponentDecoratorHandler.analyze (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:145:47)
    at TraitCompiler.analyzeTrait (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:346:40)
    at analyze (C:\Users\Utente\sites\my-project\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:298:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8) *

Rolling back to 9 restores everything.

**Expected behavior**
It should compile

**Minimal reproduction of the problem with instructions**
Just try to install the abovementioned packages and try to compile them with Angular 10.

**Please tell us about your environment:** Windows 10, npm 6.14.4

* **Angular version:** 10.0.10

* **PrimeNG version:** 10.0.0

* **Language:**
Typescript 3.9.7

* **Node (for AoT issues):** 10.21.0

**Comment by cagataycivici** [comment]
Unable to replicate with PrimeNG 10.0.0, if the issue persists please create a new ticket with a test case reproducing the issue e.g. stackblitz or a github repo and it will be reviewed by our team once again.
